CREATE TABLE `dryclean_receipt_intakes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tenantId` varchar(64) NOT NULL DEFAULT 'default',
  `orderId` int,
  `receiptImageKey` varchar(512) NOT NULL,
  `receiptImageUrl` text,
  `assignedCustomerPhone` varchar(30),
  `assignedCustomerName` varchar(255),
  `assignedCustomerUnit` varchar(50),
  `assignedBuildingSlug` varchar(100),
  `dryCleanerRetailTotalCents` int NOT NULL DEFAULT 0,
  `partnerDiscountPercent` int NOT NULL DEFAULT 40,
  `partnerCostCents` int NOT NULL DEFAULT 0,
  `laundryButlerRetailSubtotalCents` int NOT NULL DEFAULT 0,
  `customerDiscountPercentAtDraft` int NOT NULL DEFAULT 0,
  `customerTotalCentsAtDraft` int NOT NULL DEFAULT 0,
  `estimatedGrossMarginCents` int NOT NULL DEFAULT 0,
  `parseJson` json,
  `matchJson` json,
  `status` enum('uploaded','parsed','reviewed','order_created','failed') NOT NULL DEFAULT 'uploaded',
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `dryclean_receipt_intakes_id` PRIMARY KEY(`id`)
);
