ALTER TABLE `commercial_account_contacts`
  ADD COLUMN `relationshipType` enum('decision_maker','gatekeeper','champion','concierge','front_desk','security','operations','other','unknown') NOT NULL DEFAULT 'unknown' AFTER `phone`,
  ADD COLUMN `preferredChannel` enum('email','sms','phone','unknown') NOT NULL DEFAULT 'unknown' AFTER `relationshipType`,
  ADD COLUMN `source` varchar(96) NOT NULL DEFAULT 'unknown' AFTER `preferredChannel`,
  ADD COLUMN `notes` text NULL AFTER `sourcedAt`;

ALTER TABLE `commercial_account_locations`
  MODIFY COLUMN `latitude` decimal(10,7) NULL,
  MODIFY COLUMN `longitude` decimal(10,7) NULL;

ALTER TABLE `commercial_opportunities`
  MODIFY COLUMN `estimatedAnnualValueCents` int NULL;

ALTER TABLE `commercial_pipeline_records`
  MODIFY COLUMN `estimatedContractValueCents` int NULL;

CREATE TABLE `commercial_mission_irl_step_details` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `missionId` int NOT NULL,
  `missionStepId` int NOT NULL,
  `stepType` enum('generic','wardrobe_review','route_stop','collateral_pickup','purchase_stop','sales_training','field_visit','debrief') NOT NULL DEFAULT 'generic',
  `status` enum('locked','ready','active','awaiting_review','rejected','completed','skipped','cancelled') NOT NULL DEFAULT 'locked',
  `instructionText` text NULL,
  `revealPolicy` enum('sequential','immediate','admin_only') NOT NULL DEFAULT 'sequential',
  `destinationName` varchar(255) NULL,
  `destinationAddress` varchar(512) NULL,
  `destinationLatitude` decimal(10,7) NULL,
  `destinationLongitude` decimal(10,7) NULL,
  `mapsUrl` varchar(2048) NULL,
  `countdownDurationSeconds` int NULL,
  `startedAt` timestamp NULL,
  `deadlineAt` timestamp NULL,
  `proofRequirement` enum('none','confirmation','photo','photo_optional') NOT NULL DEFAULT 'none',
  `referenceImageUrl` varchar(2048) NULL,
  `instructionVideoUrl` varchar(2048) NULL,
  `pinnedCoachingArtifactId` varchar(36) NULL,
  `verificationState` enum('not_required','pending','approved','rejected','overridden') NOT NULL DEFAULT 'not_required',
  `proofAssetId` varchar(36) NULL,
  `reviewedBy` varchar(128) NULL,
  `reviewedAt` timestamp NULL,
  `rejectionReason` text NULL,
  `fulfillmentMode` enum('not_applicable','live_provider','staged_demo','manual_fulfillment') NOT NULL DEFAULT 'not_applicable',
  `metadataJson` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_mission_irl_step_details_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_irl_step_details_tenant_step` UNIQUE (`tenantId`,`missionStepId`),
  INDEX `idx_commercial_irl_step_details_tenant_mission` (`tenantId`,`missionId`,`missionStepId`)
);

CREATE TABLE `commercial_mission_dispatches` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `missionId` int NOT NULL,
  `assignedTo` varchar(128) NOT NULL,
  `handoffId` varchar(36) NULL,
  `dispatchPolicy` enum('manual','on_game_complete') NOT NULL DEFAULT 'manual',
  `channel` enum('in_app','sms') NOT NULL,
  `status` enum('queued','sent','failed','opened','not_configured','cancelled') NOT NULL DEFAULT 'queued',
  `destinationPath` varchar(1024) NOT NULL,
  `queuedAt` timestamp NOT NULL DEFAULT (now()),
  `sentAt` timestamp NULL,
  `failedAt` timestamp NULL,
  `openedAt` timestamp NULL,
  `providerMessageId` varchar(255) NULL,
  `failureReason` text NULL,
  `requestId` varchar(36) NOT NULL,
  `createdBy` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_mission_dispatches_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_dispatches_tenant_request_channel` UNIQUE (`tenantId`,`requestId`,`channel`),
  INDEX `idx_commercial_dispatches_tenant_mission` (`tenantId`,`missionId`,`createdAt`),
  INDEX `idx_commercial_dispatches_tenant_assignee_status` (`tenantId`,`assignedTo`,`status`,`createdAt`)
);

CREATE TABLE `dayforge_evidence_uploads` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `missionId` int NOT NULL,
  `missionStepId` int NOT NULL,
  `submitterId` varchar(128) NOT NULL,
  `storageKey` varchar(1024) NOT NULL,
  `contentHash` varchar(64) NOT NULL,
  `mimeType` varchar(96) NOT NULL,
  `sizeBytes` int NOT NULL,
  `attemptNumber` int NOT NULL DEFAULT 1,
  `submittedAt` timestamp NOT NULL DEFAULT (now()),
  `reviewStatus` enum('pending','approved','rejected','overridden','superseded') NOT NULL DEFAULT 'pending',
  `reviewerId` varchar(128) NULL,
  `reviewedAt` timestamp NULL,
  `reviewNote` text NULL,
  `rejectionReason` text NULL,
  `previousProofId` varchar(36) NULL,
  `requestId` varchar(36) NOT NULL,
  `purgeAfter` timestamp NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `dayforge_evidence_uploads_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_proofs_tenant_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_dayforge_evidence_tenant_step` (`tenantId`,`missionId`,`missionStepId`,`reviewStatus`,`submittedAt`),
  INDEX `idx_dayforge_evidence_purge_after` (`purgeAfter`)
);

CREATE TABLE `dayforge_evidence_object_deletions` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `evidenceUploadId` varchar(36) NULL,
  `storageKey` varchar(1024) NULL,
  `storageKeyHash` varchar(64) NOT NULL,
  `reason` enum('upload_guard','upload_orphan','retention_expiry','manual') NOT NULL,
  `status` enum('guarded','attached','queued','in_progress','retry','succeeded','permanent_failure') NOT NULL DEFAULT 'guarded',
  `attemptCount` int NOT NULL DEFAULT 0,
  `leaseId` varchar(36) NULL,
  `lastAttemptAt` timestamp NULL,
  `nextAttemptAt` timestamp NULL,
  `deletedAt` timestamp NULL,
  `lastErrorCode` varchar(96) NULL,
  `lastErrorMessage` text NULL,
  `requestId` varchar(191) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `dayforge_evidence_object_deletions_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_dayforge_evidence_deletions_tenant_request` UNIQUE (`tenantId`,`requestId`),
  CONSTRAINT `uq_dayforge_evidence_deletions_tenant_storage_hash` UNIQUE (`tenantId`,`storageKeyHash`),
  INDEX `idx_dayforge_evidence_deletions_tenant_evidence` (`tenantId`,`evidenceUploadId`),
  INDEX `idx_dayforge_evidence_deletions_retry` (`status`,`nextAttemptAt`,`createdAt`)
);

CREATE TABLE `commercial_mission_coaching_artifacts` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `missionId` int NOT NULL,
  `missionStepId` int NULL,
  `scopeKey` varchar(64) NOT NULL,
  `accountId` int NOT NULL,
  `generationStatus` enum('pending','generated','fallback','failed') NOT NULL,
  `provider` varchar(64) NOT NULL,
  `modelId` varchar(191) NULL,
  `promptVersion` varchar(64) NOT NULL,
  `contextHash` varchar(64) NOT NULL,
  `cacheKey` varchar(191) NULL,
  `requestId` varchar(36) NOT NULL,
  `version` int NOT NULL,
  `generatedAt` timestamp NULL,
  `structuredOutputJson` json NULL,
  `evidenceReferencesJson` json NULL,
  `claimsJson` json NULL,
  `failureCode` varchar(96) NULL,
  `fallbackCode` varchar(96) NULL,
  `requestedBy` varchar(128) NOT NULL,
  `generationLeaseUntil` timestamp NULL,
  `generationAttemptCount` int NOT NULL DEFAULT 0,
  `supersededAt` timestamp NULL,
  `active` boolean NOT NULL DEFAULT true,
  `latencyMs` int NULL,
  `inputTokens` int NULL,
  `outputTokens` int NULL,
  `estimatedCostMicros` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_mission_coaching_artifacts_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_coaching_tenant_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_commercial_coaching_tenant_cache_key` (`tenantId`,`cacheKey`),
  CONSTRAINT `uq_commercial_coaching_tenant_mission_scope_version` UNIQUE (`tenantId`,`missionId`,`scopeKey`,`version`),
  INDEX `idx_commercial_coaching_tenant_context` (`tenantId`,`missionId`,`contextHash`,`promptVersion`),
  INDEX `idx_commercial_coaching_tenant_mission_active` (`tenantId`,`missionId`,`active`,`createdAt`)
);

CREATE TABLE `commercial_campaign_links` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `accountId` int NOT NULL,
  `missionId` int NOT NULL,
  `pipelineId` int NULL,
  `campaignName` varchar(191) NOT NULL,
  `placement` varchar(191) NOT NULL,
  `collateralVersion` varchar(96) NOT NULL,
  `salespersonId` varchar(128) NOT NULL,
  `referringContactId` int NULL,
  `buildingSlug` varchar(100) NULL,
  `offerKey` varchar(128) NULL,
  `tokenHash` varchar(64) NOT NULL,
  `status` enum('active','expired','revoked') NOT NULL DEFAULT 'active',
  `expiresAt` timestamp NULL,
  `revokedAt` timestamp NULL,
  `requestId` varchar(36) NOT NULL,
  `createdBy` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_campaign_links_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_campaign_links_token` UNIQUE (`tokenHash`),
  CONSTRAINT `uq_commercial_campaign_links_tenant_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_commercial_campaign_links_tenant_mission` (`tenantId`,`missionId`,`createdAt`)
);

CREATE TABLE `commercial_customer_acquisition_sources` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `customerIdentityKey` varchar(64) NOT NULL,
  `serviceLocationKey` varchar(64) NOT NULL,
  `campaignLinkId` varchar(36) NULL,
  `accountId` int NOT NULL,
  `missionId` int NOT NULL,
  `pipelineId` int NULL,
  `referringContactId` int NULL,
  `sourceType` enum('explicit_campaign','trusted_property','manual') NOT NULL,
  `firstTouchAt` timestamp NOT NULL,
  `status` enum('active','review_required','removed') NOT NULL DEFAULT 'active',
  `requestId` varchar(36) NOT NULL,
  `createdBy` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_customer_acquisition_sources_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_acquisition_source_identity_location` UNIQUE (`tenantId`,`customerIdentityKey`,`serviceLocationKey`),
  CONSTRAINT `uq_commercial_acquisition_source_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_commercial_acquisition_source_campaign` (`tenantId`,`campaignLinkId`,`firstTouchAt`)
);

CREATE TABLE `commercial_order_acquisition_attributions` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `orderId` int NOT NULL,
  `firstTouchSourceId` varchar(36) NULL,
  `orderCampaignLinkId` varchar(36) NULL,
  `accountId` int NOT NULL,
  `missionId` int NOT NULL,
  `pipelineId` int NULL,
  `commercialCustomerId` int NULL,
  `referringContactId` int NULL,
  `customerIdentityKey` varchar(64) NOT NULL,
  `serviceLocationKey` varchar(64) NOT NULL,
  `sourceType` enum('explicit_campaign','inherited_first_touch','trusted_property','manual') NOT NULL,
  `confidence` enum('high','medium','low') NOT NULL,
  `attributionReason` text NOT NULL,
  `firstTouchAt` timestamp NULL,
  `conversionAt` timestamp NOT NULL,
  `reviewState` enum('pending','attributed','review_required','excluded','reversed') NOT NULL,
  `reviewedBy` varchar(128) NULL,
  `reviewedAt` timestamp NULL,
  `reviewReason` text NULL,
  `requestId` varchar(36) NOT NULL,
  `createdBy` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `commercial_order_acquisition_attributions_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_order_acquisition_tenant_order` UNIQUE (`tenantId`,`orderId`),
  CONSTRAINT `uq_commercial_order_acquisition_tenant_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_commercial_order_acquisition_tenant_review` (`tenantId`,`reviewState`,`createdAt`),
  INDEX `idx_commercial_order_acquisition_tenant_campaign` (`tenantId`,`orderCampaignLinkId`,`conversionAt`)
);

CREATE TABLE `commercial_attribution_corrections` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `acquisitionAttributionId` varchar(36) NOT NULL,
  `orderId` int NOT NULL,
  `previousStateJson` json NOT NULL,
  `correctedStateJson` json NOT NULL,
  `reason` text NOT NULL,
  `correctedBy` varchar(128) NOT NULL,
  `requestId` varchar(36) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `commercial_attribution_corrections_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_commercial_attribution_corrections_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_commercial_attribution_corrections_attribution` (`tenantId`,`acquisitionAttributionId`,`createdAt`)
);

CREATE TABLE `order_payment_projections` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `orderId` int NOT NULL,
  `provider` varchar(64) NOT NULL,
  `providerPaymentId` varchar(255) NULL,
  `currency` varchar(3) NOT NULL,
  `state` enum('unpaid','paid','partially_refunded','refunded','cancelled','review_required') NOT NULL,
  `capturedCents` int NULL,
  `refundedCents` int NULL,
  `netPaidCents` int NULL,
  `paidAt` timestamp NULL,
  `providerUpdatedAt` timestamp NULL,
  `lastReconciledAt` timestamp NOT NULL,
  `version` int NOT NULL DEFAULT 1,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `order_payment_projections_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_order_payment_projections_tenant_order` UNIQUE (`tenantId`,`orderId`),
  INDEX `idx_order_payment_projections_provider_payment` (`provider`,`providerPaymentId`)
);

CREATE TABLE `order_payment_events` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `orderId` int NOT NULL,
  `provider` varchar(64) NOT NULL,
  `providerEventId` varchar(255) NULL,
  `eventType` varchar(96) NOT NULL,
  `currency` varchar(3) NULL,
  `capturedCents` int NULL,
  `refundedCents` int NULL,
  `netPaidCents` int NULL,
  `payloadDigest` varchar(64) NULL,
  `occurredAt` timestamp NOT NULL,
  `requestId` varchar(191) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `order_payment_events_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_order_payment_events_provider_event` UNIQUE (`provider`,`providerEventId`),
  CONSTRAINT `uq_order_payment_events_tenant_request` UNIQUE (`tenantId`,`requestId`),
  INDEX `idx_order_payment_events_tenant_order` (`tenantId`,`orderId`,`occurredAt`)
);

ALTER TABLE `commercial_order_attributions`
  ADD COLUMN `acquisitionAttributionId` varchar(36) NULL AFTER `orderId`,
  ADD COLUMN `status` enum('active','reversed','financial_review') NOT NULL DEFAULT 'active' AFTER `attributionType`,
  ADD COLUMN `currency` varchar(3) NULL AFTER `status`,
  ADD COLUMN `capturedCents` int NULL AFTER `currency`,
  ADD COLUMN `refundedCents` int NULL AFTER `capturedCents`,
  ADD COLUMN `netPaidCents` int NULL AFTER `refundedCents`,
  ADD COLUMN `financialReviewReason` varchar(191) NULL AFTER `createdBy`,
  ADD COLUMN `lastReconciledAt` timestamp NULL AFTER `financialReviewReason`;

CREATE TABLE `dayforge_auth_continuations` (
  `id` varchar(36) NOT NULL,
  `tokenHash` varchar(64) NOT NULL,
  `tenantId` varchar(64) NULL,
  `userOpenId` varchar(64) NULL,
  `previewSessionId` varchar(64) NULL,
  `previewCandidateKey` varchar(191) NULL,
  `phoneHandoffId` varchar(36) NULL,
  `returnTo` varchar(2048) NULL,
  `onboardingSessionId` varchar(36) NULL,
  `status` enum('active','consumed','expired','revoked') NOT NULL DEFAULT 'active',
  `expiresAt` timestamp NOT NULL,
  `consumedAt` timestamp NULL,
  `consumedBy` varchar(128) NULL,
  `requestId` varchar(36) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `dayforge_auth_continuations_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_dayforge_auth_continuations_token` UNIQUE (`tokenHash`),
  CONSTRAINT `uq_dayforge_auth_continuations_request` UNIQUE (`requestId`),
  INDEX `idx_dayforge_auth_continuations_preview` (`previewSessionId`,`status`,`expiresAt`),
  INDEX `idx_dayforge_auth_continuations_handoff` (`phoneHandoffId`,`status`,`expiresAt`)
);

ALTER TABLE `dayforge_saas_onboarding_sessions`
  ADD COLUMN `authContinuationId` varchar(36) NULL AFTER `stripeSubscriptionId`,
  ADD INDEX `idx_dayforge_saas_onboarding_continuation` (`authContinuationId`);
