CREATE TABLE IF NOT EXISTS `sales_intel_ingestion_jobs` (
  `id` varchar(36) NOT NULL,
  `jobKey` varchar(191) NOT NULL,
  `sourceArtifactId` varchar(36) NOT NULL,
  `actorId` varchar(128) NOT NULL,
  `jobType` enum('instagram_media_to_teachings') NOT NULL,
  `pipelineVersion` varchar(96) NOT NULL,
  `state` enum('queued','processing','completed','failed') NOT NULL DEFAULT 'queued',
  `attemptCount` int NOT NULL DEFAULT 0,
  `maxAttempts` int NOT NULL DEFAULT 5,
  `nextAttemptAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `leaseOwner` varchar(96) NULL,
  `leaseExpiresAt` timestamp NULL,
  `failureCode` varchar(96) NULL,
  `failureMessage` varchar(500) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL,
  CONSTRAINT `sales_intel_ingestion_jobs_id` PRIMARY KEY (`id`),
  CONSTRAINT `uq_sales_intel_ingestion_job_key` UNIQUE (`jobKey`),
  INDEX `idx_sales_intel_ingestion_jobs_due` (`state`, `nextAttemptAt`),
  INDEX `idx_sales_intel_ingestion_jobs_lease` (`leaseExpiresAt`),
  INDEX `idx_sales_intel_ingestion_jobs_source` (`sourceArtifactId`, `createdAt`)
);
