CREATE TABLE IF NOT EXISTS `entity_locations` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `entityType` enum('customer','building','commercial_prospect') NOT NULL,
  `entityKey` varchar(191) NOT NULL,
  `sourceAddress` varchar(512) NOT NULL,
  `normalizedSourceAddress` varchar(512) NOT NULL,
  `canonicalAddress` varchar(512),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `googlePlaceId` varchar(255),
  `geocodeStatus` enum('pending','success','missing_address','ambiguous','provider_failure','transient_failure','unconfigured') NOT NULL DEFAULT 'pending',
  `geocodeProvider` varchar(64),
  `geocodedAt` timestamp NULL,
  `geocodeError` varchar(512),
  `lastAttemptAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_entity_locations_tenant_entity` (`tenantId`,`entityType`,`entityKey`),
  KEY `idx_entity_locations_tenant_status` (`tenantId`,`geocodeStatus`),
  KEY `idx_entity_locations_tenant_address` (`tenantId`,`normalizedSourceAddress`)
);

CREATE TABLE IF NOT EXISTS `tower_wars_promises` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `buildingId` enum('opus_la','century_park_east') NOT NULL,
  `customerIdentity` varchar(191),
  `promiseType` enum('offer_insert','referral_card','loyalty_reward','thank_you_presentation','other') NOT NULL,
  `sourceText` text NOT NULL,
  `quantity` int,
  `permissionStatus` enum('not_required_physical_fulfillment','recorded','not_recorded','revoked') NOT NULL,
  `permissionChannel` enum('physical_delivery','sms','email','phone','none') NOT NULL,
  `permissionEvidence` text,
  `sourceReference` varchar(512) NOT NULL,
  `idempotencyKey` varchar(191) NOT NULL,
  `fulfilledAt` timestamp NULL,
  `fulfilledBy` varchar(128),
  `fulfillmentEvidence` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tower_wars_promises_tenant_key` (`tenantId`,`idempotencyKey`),
  KEY `idx_tower_wars_promises_building_open` (`tenantId`,`buildingId`,`fulfilledAt`)
);
