-- Candy Bar V0 durable orchestration. Additive only.
-- NOT applied to production until Adam approves (same gate as 0077).
-- scripts/migrate.mjs does not include this file.

CREATE TABLE IF NOT EXISTS candy_bar_workflows (
  id VARCHAR(36) PRIMARY KEY,
  tenantId VARCHAR(64) NOT NULL,
  operatorUserId VARCHAR(128) NOT NULL,
  repository VARCHAR(191) NOT NULL,
  currentGoal TEXT NOT NULL,
  goalVersion INT NOT NULL DEFAULT 1,
  roadmapContext TEXT NULL,
  protectedAreasJson JSON NULL,
  knownParallelWorkJson JSON NULL,
  nonGoalsJson JSON NULL,
  providerFallbackPolicyJson JSON NOT NULL,
  autoPlanNext TINYINT(1) NOT NULL DEFAULT 0,
  preferredArchitect VARCHAR(32) NOT NULL DEFAULT 'anthropic',
  preferredReviewer VARCHAR(32) NOT NULL DEFAULT 'xai_grok',
  preferredEngineer VARCHAR(32) NOT NULL DEFAULT 'cursor',
  maxStepsPerRun INT NOT NULL DEFAULT 40,
  maxRepairIterations INT NOT NULL DEFAULT 3,
  maxReconcileRounds INT NOT NULL DEFAULT 2,
  maxWallClockMs INT NOT NULL DEFAULT 21600000,
  maxProviderFailures INT NOT NULL DEFAULT 5,
  budgetCents INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_candy_bar_workflow_owner_repo (tenantId, operatorUserId, repository),
  KEY idx_candy_bar_workflow_tenant (tenantId, updatedAt)
);

CREATE TABLE IF NOT EXISTS candy_bar_runs (
  id VARCHAR(36) PRIMARY KEY,
  tenantId VARCHAR(64) NOT NULL,
  operatorUserId VARCHAR(128) NOT NULL,
  workflowId VARCHAR(36) NOT NULL,
  workflowType VARCHAR(64) NOT NULL DEFAULT 'engineering_slice',
  goalSnapshotJson JSON NOT NULL,
  state VARCHAR(32) NOT NULL,
  authorityLevel VARCHAR(64) NULL,
  iteration INT NOT NULL DEFAULT 0,
  repairIteration INT NOT NULL DEFAULT 0,
  reconcileRound INT NOT NULL DEFAULT 0,
  stepCount INT NOT NULL DEFAULT 0,
  providerFailureCount INT NOT NULL DEFAULT 0,
  estimatedSpendCents INT NULL,
  spendKnown TINYINT(1) NOT NULL DEFAULT 0,
  currentStepId VARCHAR(36) NULL,
  parentRunId VARCHAR(36) NULL,
  repository VARCHAR(191) NOT NULL,
  baseBranch VARCHAR(128) NOT NULL DEFAULT 'main',
  baseSha VARCHAR(64) NULL,
  plannedAgainstSha VARCHAR(64) NULL,
  candidateBranch VARCHAR(191) NULL,
  candidatePrNumber INT NULL,
  candidatePrUrl VARCHAR(512) NULL,
  candidateHeadSha VARCHAR(64) NULL,
  engineerSessionId VARCHAR(128) NULL,
  blocker TEXT NULL,
  humanGateReason VARCHAR(64) NULL,
  mergeAttempted TINYINT(1) NOT NULL DEFAULT 0,
  deployAttempted TINYINT(1) NOT NULL DEFAULT 0,
  productionMigrationAttempted TINYINT(1) NOT NULL DEFAULT 0,
  nextPlanSpawned TINYINT(1) NOT NULL DEFAULT 0,
  leaseOwner VARCHAR(128) NULL,
  leaseExpiresAt TIMESTAMP NULL,
  nextRetryAt TIMESTAMP NULL,
  lastError TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  startedAt TIMESTAMP NULL,
  completedAt TIMESTAMP NULL,
  KEY idx_candy_bar_runs_tenant_state (tenantId, state, updatedAt),
  KEY idx_candy_bar_runs_operator (tenantId, operatorUserId, createdAt),
  KEY idx_candy_bar_runs_lease (state, leaseExpiresAt),
  KEY idx_candy_bar_runs_workflow (workflowId, createdAt)
);

CREATE TABLE IF NOT EXISTS candy_bar_steps (
  id VARCHAR(36) PRIMARY KEY,
  runId VARCHAR(36) NOT NULL,
  kind VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attemptNumber INT NOT NULL DEFAULT 0,
  provider VARCHAR(32) NULL,
  providerSessionId VARCHAR(128) NULL,
  inputArtifactIdsJson JSON NULL,
  outputArtifactIdsJson JSON NULL,
  error TEXT NULL,
  blocker TEXT NULL,
  requiresHumanApproval TINYINT(1) NOT NULL DEFAULT 0,
  inputTokens INT NULL,
  outputTokens INT NULL,
  estimatedCostCents INT NULL,
  costKnown TINYINT(1) NOT NULL DEFAULT 0,
  leaseOwner VARCHAR(128) NULL,
  leaseExpiresAt TIMESTAMP NULL,
  idempotencyKey VARCHAR(191) NOT NULL,
  startedAt TIMESTAMP NULL,
  completedAt TIMESTAMP NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_candy_bar_step_idempotency (idempotencyKey),
  KEY idx_candy_bar_steps_run (runId, createdAt),
  KEY idx_candy_bar_steps_lease (status, leaseExpiresAt)
);

CREATE TABLE IF NOT EXISTS candy_bar_artifacts (
  id VARCHAR(36) PRIMARY KEY,
  runId VARCHAR(36) NOT NULL,
  type VARCHAR(64) NOT NULL,
  schemaVersion INT NOT NULL DEFAULT 1,
  producer VARCHAR(128) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  contentJson JSON NOT NULL,
  metadataJson JSON NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_candy_bar_artifacts_run_type (runId, type, createdAt)
);

CREATE TABLE IF NOT EXISTS candy_bar_approvals (
  id VARCHAR(36) PRIMARY KEY,
  runId VARCHAR(36) NOT NULL,
  tenantId VARCHAR(64) NOT NULL,
  operatorUserId VARCHAR(128) NOT NULL,
  action VARCHAR(64) NOT NULL,
  reason TEXT NULL,
  actorUserId VARCHAR(128) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_candy_bar_approvals_run (runId, createdAt),
  KEY idx_candy_bar_approvals_tenant (tenantId, operatorUserId, createdAt)
);
