-- Mitch v1: Durable Game Production Operating System Tables
CREATE TABLE IF NOT EXISTS `mitch_game_production_states` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `storedRowId` varchar(64) NULL,
  `title` varchar(191) NOT NULL,
  `lifecycleState` varchar(64) NOT NULL DEFAULT 'concept',
  `realBusinessBinding` text,
  `coreMechanic` text,
  `companionDependency` varchar(64),
  `requiredAssetsJson` json,
  `blockingDependenciesJson` json,
  `currentAvailableBuildId` varchar(128),
  `lastVerifiedBuildId` varchar(128),
  `creativeAcceptanceState` varchar(64) NOT NULL DEFAULT 'pending',
  `creativeAcceptanceNote` text,
  `creativeAcceptanceDecidedAt` timestamp NULL,
  `releaseState` varchar(64) NOT NULL DEFAULT 'unreleased',
  `releasedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mitch_game_production_state` (`tenantId`, `gameId`),
  KEY `idx_mitch_game_lifecycle` (`tenantId`, `lifecycleState`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_milestones` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `milestoneKey` varchar(64) NOT NULL,
  `sequence` int NOT NULL DEFAULT 0,
  `title` varchar(191) NOT NULL,
  `desiredPlayerVisibleResult` text NOT NULL,
  `acceptanceCriteriaJson` json NOT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'pending',
  `currentAvailableBuildId` varchar(128),
  `lastVerifiedBuildId` varchar(128),
  `blockedReason` text,
  `isHumanCreativeBlocker` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mitch_milestones` (`tenantId`, `gameId`, `milestoneKey`),
  KEY `idx_mitch_milestones_status` (`tenantId`, `gameId`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_work_orders` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `milestoneId` varchar(36) NOT NULL,
  `milestoneKey` varchar(64) NOT NULL,
  `title` varchar(191) NOT NULL,
  `desiredPlayerVisibleResult` text NOT NULL,
  `acceptanceCriteriaJson` json NOT NULL,
  `canonConstraintsJson` json NOT NULL,
  `relevantDependenciesJson` json NOT NULL,
  `realBusinessEvidenceConstraintsJson` json NOT NULL,
  `baseBranch` varchar(191) NOT NULL,
  `baseSha` varchar(64) NOT NULL,
  `requiredArtifact` text NOT NULL,
  `requiredTestsJson` json NOT NULL,
  `requiredEvidenceJson` json NOT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'pending',
  `claimedBy` varchar(128),
  `claimedAt` timestamp NULL,
  `leaseExpiresAt` timestamp NULL,
  `attemptCount` int NOT NULL DEFAULT 0,
  `maxAttempts` int NOT NULL DEFAULT 3,
  `lastError` text,
  `completedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_work_orders_status` (`tenantId`, `gameId`, `status`),
  KEY `idx_mitch_work_orders_lease` (`status`, `leaseExpiresAt`),
  KEY `idx_mitch_work_orders_milestone` (`tenantId`, `milestoneId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_execution_runs` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `workOrderId` varchar(36) NOT NULL,
  `executorId` varchar(128) NOT NULL,
  `startedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL,
  `status` varchar(64) NOT NULL DEFAULT 'running',
  `returnedBranch` varchar(191),
  `returnedCommitSha` varchar(64),
  `exactBuildId` varchar(128),
  `whatChanged` text,
  `testsActuallyRunJson` json,
  `testsNotRunJson` json,
  `previewLaunchInstructions` text,
  `evidenceJson` json,
  `knownLimitations` text,
  `errorMessage` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_execution_runs_work_order` (`tenantId`, `workOrderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_builds` (
  `id` varchar(128) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `workOrderId` varchar(36) NOT NULL,
  `executionRunId` varchar(36) NOT NULL,
  `commitSha` varchar(64) NOT NULL,
  `branch` varchar(191) NOT NULL,
  `buildArtifactType` varchar(64) NOT NULL,
  `buildArtifactId` varchar(255) NOT NULL,
  `sourceCompiled` tinyint(1) NOT NULL DEFAULT 0,
  `unitTestsPassed` tinyint(1) NOT NULL DEFAULT 0,
  `isVerified` tinyint(1) NOT NULL DEFAULT 0,
  `verifiedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_builds_game` (`tenantId`, `gameId`, `isVerified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_qa_runs` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `milestoneId` varchar(36) NOT NULL,
  `buildId` varchar(128) NOT NULL,
  `testerId` varchar(128) NOT NULL,
  `scenario` text NOT NULL,
  `expectedBehavior` text NOT NULL,
  `observedBehavior` text NOT NULL,
  `gameActuallyExercised` tinyint(1) NOT NULL DEFAULT 0,
  `acceptancePassed` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(64) NOT NULL,
  `evidenceArtifact` text NOT NULL,
  `issueId` varchar(36),
  `previousFailedQaRunId` varchar(36),
  `isRetest` tinyint(1) NOT NULL DEFAULT 0,
  `completedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_qa_runs_build` (`tenantId`, `buildId`, `status`),
  KEY `idx_mitch_qa_runs_milestone` (`tenantId`, `milestoneId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_issues` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `milestoneId` varchar(36) NOT NULL,
  `originatingQaRunId` varchar(36) NOT NULL,
  `title` varchar(191) NOT NULL,
  `description` text NOT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'open',
  `fixWorkOrderId` varchar(36),
  `fixBuildId` varchar(128),
  `closingQaRunId` varchar(36),
  `closedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_issues_status` (`tenantId`, `gameId`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mitch_audit_events` (
  `id` varchar(36) NOT NULL,
  `tenantId` varchar(64) NOT NULL,
  `gameId` varchar(64) NOT NULL,
  `eventType` varchar(64) NOT NULL,
  `actorId` varchar(128) NOT NULL,
  `detailsJson` json NOT NULL,
  `occurredAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_mitch_audit_events_game` (`tenantId`, `gameId`, `occurredAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
