import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { json, mysqlTable, varchar } from "drizzle-orm/mysql-core";
import { operationsEvents, orders } from "../../drizzle/schema";
import type { TowerWarsAttackEvent, TowerWarsBuildingId } from "../../shared/towerWars";
import { impactForAttack, repairImpacts, type TowerImpact } from "../../shared/towerWarsImpacts";
import { getDb } from "../db";
import { formatInTimeZone } from "date-fns-tz";
import { rivalrySeasonId, type rivalryHistory } from "../../shared/towerWarsSeasons";

export const towerImpacts = mysqlTable("goldline_tower_impacts", {
  id: varchar("id", { length: 64 }).primaryKey(),
  tenantId: varchar("tenantId", { length: 64 }).notNull(),
  payload: json("payload").$type<TowerImpact>().notNull(),
});
export const seasonRevisions = mysqlTable("goldline_tower_season_revisions", {
  id: varchar("id", { length: 64 }).primaryKey(),
  tenantId: varchar("tenantId", { length: 64 }).notNull(),
  seasonId: varchar("seasonId", { length: 10 }).notNull(),
  payload: json("payload").notNull(),
});

/** Content-addressed projection revisions retain previous results for audit.
 * No business event is changed or generated by a revision. */
export async function persistSeasonRevisions(tenantId: string, seasons: ReturnType<typeof rivalryHistory>) {
  const db = await getDb();
  if (!db) return;
  for (const season of seasons) {
    const payload = { seasonId: season.seasonId, localStart: season.localStart, localEnd: season.localEnd,
      status: season.status, result: season.result, winner: season.winner, loser: season.loser,
      buildings: season.state.buildings, attacks: season.state.attacks,
      classification: "game_projection", provenanceClass: "generated_game_fiction" };
    const id = createHash("sha256").update(JSON.stringify([tenantId, payload])).digest("hex");
    await db.insert(seasonRevisions).values({ id, tenantId, seasonId: season.seasonId, payload: { ...payload, revision: id } })
      .onDuplicateKeyUpdate({ set: { id } });
  }
}

export async function listSeasonRevisions(tenantId: string, seasonId: string) {
  const db = await getDb();
  if (!db) return [];
  return db.select().from(seasonRevisions).where(and(eq(seasonRevisions.tenantId, tenantId), eq(seasonRevisions.seasonId, seasonId)));
}

/** Only canonical server compilation calls this, never a replay reducer.
 * Upsert preserves a single record per attack; geometry derives from identity. */
export async function persistCanonicalImpacts(tenantId: string, attacks: readonly TowerWarsAttackEvent[], options: { persist?: boolean; before?: Date } = {}) {
  const db = await getDb();
  if (!db) return [];
  const evidence = await db.select({ orderId: orders.id, status: orders.status,
    buildingSlug: operationsEvents.buildingSlug, occurredAt: operationsEvents.actualEventTimestamp })
    .from(operationsEvents).innerJoin(orders, and(eq(orders.id, operationsEvents.orderId), eq(orders.tenantId, tenantId)))
    .where(and(eq(operationsEvents.tenantId, tenantId), eq(operationsEvents.sourceEventType, "pickup_completed"), eq(operationsEvents.eventStatus, "completed")));
  const repairs = evidence.flatMap(row => {
    if (options.before && row.occurredAt >= options.before) return [];
    const slug = row.buildingSlug?.replace(/[-_]/g, "");
    const buildingId: TowerWarsBuildingId | null = slug === "opusla" ? "opus_la" : slug === "centuryparkeast" ? "century_park_east" : null;
    return buildingId ? [{ orderId: String(row.orderId), buildingId, collectedAt: row.occurredAt.toISOString(), valid: ["collected", "processing", "ready", "delivered"].includes(row.status) }] : [];
  });
  const impacts = repairImpacts(attacks.map(a => impactForAttack(a,
    rivalrySeasonId(formatInTimeZone(a.occurredAt, "America/Los_Angeles", "yyyy-MM-dd")))), repairs);
  for (const payload of options.persist === false ? [] : impacts) {
    const id = createHash("sha256").update(JSON.stringify([tenantId, payload.attackId])).digest("hex");
    await db.insert(towerImpacts).values({ id, tenantId, payload }).onDuplicateKeyUpdate({ set: { payload } });
  }
  return impacts;
}
