import { useLocation } from "wouter";
import { ArrowLeft, Building2, House } from "lucide-react";
import { trpc } from "@/lib/trpc";

function dollars(value:number|null|undefined){return value==null?"Unknown":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value/100)}

export default function CustomerVault(){
  const [location,navigate]=useLocation();
  const raw=location.startsWith("/product/customer/")?location.slice("/product/customer/".length):null;
  const assetId=raw?decodeURIComponent(raw):null;
  const list=trpc.system.customerAssets.list.useQuery(undefined,{enabled:!assetId});
  const detail=trpc.system.customerAssets.detail.useQuery({assetId:assetId??"missing"},{enabled:Boolean(assetId),retry:false});
  if(assetId){const asset=detail.data;return <section className="cc-vault"><button className="cc-button" onClick={()=>navigate("/product/customers")}><ArrowLeft size={14}/> Customer Vault</button>{detail.isLoading?<div className="cc-empty">Loading persisted customer state…</div>:!asset?<div className="cc-empty">{detail.error?.message}</div>:<><p className="cc-eyebrow" style={{marginTop:24}}>{asset.kind} asset</p><h1 className="cc-section-title">{asset.displayName}</h1><p>{asset.property.address}{asset.property.unit?` · Unit ${asset.property.unit}`:""}</p><div className="cc-vault-grid"><div className="cc-customer-card"><p>Lifetime collected</p><div className="cc-money">{dollars(asset.lifetimeValue.value)}</div><small>{asset.lifetimeValue.provenance}</small></div><div className="cc-customer-card"><p>Outstanding</p><div className="cc-money">{dollars(asset.outstandingReceivables.value)}</div><small>{asset.outstandingReceivables.provenance}</small></div><div className="cc-customer-card"><p>Relationship health</p><h3>{asset.health.replace(/_/g," ")}</h3><p>{asset.healthReason}</p></div><div className="cc-customer-card"><p>Service history</p><h3>{asset.service.orderCount} orders</h3><p>{asset.service.serviceTypes.join(", ")}</p></div></div><section className="cc-panel" style={{marginTop:20}}><div className="cc-panel-head"><h2>Durable timeline</h2></div><div className="cc-timeline">{asset.timeline.map(item=><article className="cc-timeline-item" key={item.id}><div className="cc-time">{new Date(item.occurredAt).toLocaleDateString()}</div><div className="cc-item-copy"><h3>{item.title}</h3><p>{item.sourceReference} · {item.verificationClass}</p></div>{item.amountCents!=null?<span className="cc-money">{dollars(item.amountCents)}</span>:null}</article>)}</div></section><div className="cc-quality">{asset.dataQuality.warnings.join(" · ")}</div></>}</section>}
  return <section className="cc-vault"><p className="cc-eyebrow">HQ · Canonical assets</p><h1 className="cc-section-title">Customer Vault</h1><p className="cc-data-note">One projection shared by FIELD and HQ. No separate game-customer database.</p>{list.isLoading?<div className="cc-empty">Building customer assets…</div>:<div className="cc-vault-grid">{list.data?.map(asset=><button key={asset.id} className="cc-customer-card" style={{textAlign:"left"}} onClick={()=>navigate(`/product/customer/${encodeURIComponent(asset.id)}`)}>{asset.kind==="commercial"?<Building2/>:<House/>}<h3>{asset.displayName}</h3><p>{asset.property.address??"Address unavailable"}</p><div className="cc-money">{dollars(asset.lifetimeValue.value)}</div><span className="cc-badge">{asset.health.replace(/_/g," ")}</span></button>)}</div>}</section>
}
