import { useState } from "react";
import { ArrowLeft, CheckCircle2, CircleDollarSign, Sunrise, Trophy } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function money(cents:number|null){return cents==null?"Unknown":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100)}

export default function UnloadView(){const [requestId]=useState(()=>crypto.randomUUID());const mutation=trpc.system.unload.resolveDay.useMutation();const data=mutation.data;return <section className="cc-vault"><Link href="/product/field" className="cc-button"><ArrowLeft size={14}/> Field</Link><p className="cc-eyebrow" style={{marginTop:24}}>End-of-day resolution · {localDate()}</p><h1 className="cc-section-title">Unload the Day</h1><p className="cc-data-note">Opening this screen creates no business gain. Resolution is built only from durable events and is idempotent for this date.</p>{!data?<button className="cc-button primary" style={{marginTop:24}} disabled={mutation.isPending} onClick={()=>mutation.mutate({businessDate:localDate(),requestId})}>{mutation.isPending?"Resolving durable events…":"Resolve today"}</button>:<><div className="cc-vault-grid"><div className="cc-customer-card"><CheckCircle2/><p>Completed work</p><h3>{data.completedWork.length}</h3></div><div className="cc-customer-card"><CircleDollarSign/><p>Money events</p><h3>{data.moneyEvents.length}</h3></div><div className="cc-customer-card"><Trophy/><p>Motivational points</p><h3>{data.motivationalAwards.reduce((sum,item)=>sum+item.points,0)}</h3></div><div className="cc-customer-card"><Sunrise/><p>Tomorrow</p><h3>{data.tomorrowState.itemCount} items · {data.tomorrowState.blockerCount} blockers</h3></div></div><section className="cc-panel" style={{marginTop:20}}><div className="cc-panel-head"><h2>World changes</h2><span className="cc-badge">durable only</span></div>{data.worldDeltas.length?data.worldDeltas.map(delta=><article className="cc-timeline-item" key={delta.id}><div className="cc-time">{delta.verificationClass}</div><div className="cc-item-copy"><h3>{delta.title}</h3><p>{delta.sourceReference}</p></div></article>):<div className="cc-empty">No sourced world changes occurred today.</div>}</section><section className="cc-panel" style={{marginTop:16}}><div className="cc-panel-head"><h2>Verified money</h2></div>{data.moneyEvents.map(event=><article className="cc-timeline-item" key={event.id}><div className="cc-time">{event.verificationClass}</div><div className="cc-item-copy"><h3>{event.title}</h3><p>{event.sourceReference}</p></div><span className="cc-money">{money(event.amountCents)}</span></article>)}</section><div className="cc-quality">Resolution {data.id} · Source through {new Date(data.sourceThrough).toLocaleString()} · {data.dataQuality.warnings.join(" · ")}</div></>}</section>}
