import { describe, expect, it } from "vitest";
import type { ClaireDriveContext, ClaireTimelineItem, ClaireWorkCounts } from "./contextAssembler";
import { buildClaireOpeningFallback } from "./reasoning";

const zeroCounts: ClaireWorkCounts = { pickups: 0, dropoffs: 0, commercialVisits: 0, commercialCalls: 0, followUps: 0, dayDirectorCommitments: 0, blockers: 0, campaignWorkReferences: 0 };
const item = (title: string, kind: ClaireTimelineItem["kind"]): ClaireTimelineItem => ({ id: title, kind, title, subtitle: kind, urgency: "scheduled", scheduledAt: null, destination: null, sourceReference: `fixture:${title}`, whySurfaced: null, actions: [] });
function context(overrides: Partial<ClaireDriveContext> = {}): ClaireDriveContext {
  return { phase: "pre_drive", generatedAt: "2026-09-15T02:00:00.000Z", businessDate: "2026-09-14", actorId: "operator-1", truthLaw: "game_projection_never_creates_business_truth", nextFixedCommitment: null, blockers: [], relevantTimeline: [], mission: null, ...overrides };
}
const clock = (hour: "8" | "19") => ({ isoTimestamp: hour === "8" ? "2026-09-14T15:00:00.000Z" : "2026-09-15T02:00:00.000Z", timeZone: "America/Los_Angeles", businessDate: "2026-09-14", weekday: "Monday", localTime: hour === "8" ? "8:00 AM" : "7:00 PM", daypart: hour === "8" ? "morning" as const : "evening" as const, fieldSalesDayState: hour === "8" ? "open" as const : "over" as const, tomorrowBusinessDate: "2026-09-15" });
const goal = { id: "g1", tenantId: "tenant-1", operatorUserId: "operator-1", objective: "Get to 50 active customers", metricKey: "active_customers", targetValue: 50, unit: "customers", urgencyText: "ASAP", targetDate: null, source: "operator_attested" as const, sourceNote: "attested", status: "active" as const, supersededById: null, createdAt: new Date(), updatedAt: new Date() };

describe("Claire opening orientation fallback", () => {
  it("asks for an unknown goal at 8 AM", () => expect(buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: false, macroGoal: null }))).toContain("what are we actually trying to accomplish"));
  it("recognizes at 7 PM that property visits are over without ending all work", () => expect(buildClaireOpeningFallback(context({ clock: clock("19"), macroGoalKnown: false, macroGoal: null }))).toContain("property-visit window is over"));
  it("states a known goal at 7 PM", () => expect(buildClaireOpeningFallback(context({ clock: clock("19"), macroGoalKnown: true, macroGoal: goal }))).toContain("50 customers is still the target"));
  it("uses an exact complete metric", () => expect(buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: true, macroGoal: goal, verifiedMetrics: { activeCustomers: { value: 27, definition: "30 days", windowStart: "a", windowEnd: "b", sources: ["laundry_butler", "cleancloud"], unmatchedCount: 0, completeness: "complete", computedAt: "c" } } }))).toContain("count is 27"));
  it("labels a partial metric as not the total", () => expect(buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: true, macroGoal: goal, verifiedMetrics: { activeCustomers: { value: 21, definition: "30 days", windowStart: "a", windowEnd: "b", sources: ["laundry_butler"], unmatchedCount: 0, completeness: "partial", computedAt: "c" } } }))).toContain("not the full active-customer total"));
  it("omits an unavailable count", () => expect(buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: true, macroGoal: goal, verifiedMetrics: { activeCustomers: { value: null, definition: "30 days", windowStart: "a", windowEnd: "b", sources: [], unmatchedCount: 0, completeness: "unavailable", computedAt: "c" } } }))).not.toMatch(/count is/));
  it("uses explicit tomorrow zero pickups and one dropoff", () => expect(buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: true, macroGoal: goal, workPicture: { today: { businessDate: "2026-09-14", counts: zeroCounts, items: [] }, tomorrow: { businessDate: "2026-09-15", counts: { ...zeroCounts, dropoffs: 1 }, items: [] } } }))).toContain("0 pickups and 1 dropoffs"));
  it("uses three real Greystar visits, not fantasy language", () => { const result = buildClaireOpeningFallback(context({ clock: clock("8"), macroGoalKnown: true, macroGoal: goal, campaign: { campaignName: "Colosseum", active: true, completedCount: 2, remainingCount: 3, totalCount: 5, realWorldExtension: "Greystar property prospecting visits", remainingTargets: [], relationToGoal: "customer acquisition pipeline" } })); expect(result).toContain("3 Greystar property visits"); expect(result).not.toMatch(/kingdom|villain/i); });
  it("keeps empty legacy context safe", () => expect(buildClaireOpeningFallback(context())).toContain("macro goal"));
  it("allows grounded remote work after field sales are over", () => expect(buildClaireOpeningFallback(context({ clock: clock("19"), macroGoalKnown: true, macroGoal: goal, workPicture: { today: { businessDate: "2026-09-14", counts: { ...zeroCounts, followUps: 1 }, items: [item("Zeely research follow-up", "follow_up")] }, tomorrow: { businessDate: "2026-09-15", counts: zeroCounts, items: [] } } }))).toContain("can still move remotely"));
});
