/**
 * FLYER PROOF CAPTURE — Photo verification that the driver posted a flyer.
 *
 * ─── INTEGRATION INSTRUCTIONS FOR CLAUDE CODE / CODEX ───────────────────────
 *
 * This screen bridges the Mission Briefing and Signal Override phases.
 * It must be inserted as a new phase in `driverPrepMachine.ts`.
 *
 * 1. ADD PHASE to `DriverPrepPhase` union in driverPrepMachine.ts:
 *    "flyer_proof" (insert between "mission_briefing" and "signal_override")
 *
 * 2. ADD ACTION to `DriverPrepAction` union:
 *    | { type: "COMPLETE_FLYER_PROOF"; previewDataUrl?: string | null }
 *
 * 3. ADD REDUCER CASE:
 *    case "COMPLETE_FLYER_PROOF":
 *      return { ...state, phase: "signal_override" };
 *
 * 4. ADD HANDLER in DriverPrepMechanic.tsx (alongside handleStartOverride):
 *    const handleCompleteFlyerProof = useCallback((previewDataUrl?: string | null) => {
 *      dispatch({ type: "COMPLETE_FLYER_PROOF", previewDataUrl });
 *    }, []);
 *
 * 5. ADD CASE in renderPhase():
 *    case "flyer_proof":
 *      return (
 *        <FlyerProofCapture
 *          mission={args.missionTarget}
 *          onComplete={args.handleCompleteFlyerProof}
 *        />
 *      );
 *
 * 6. TRANSITION: In the MissionBriefing "FLYER POSTED — BEGIN OVERRIDE" button,
 *    change the handler from `onStartOverride` to a new `onFlyerPosted` prop
 *    that advances to "flyer_proof" instead of "signal_override" directly.
 *    OR: rename the existing handleStartOverride to handleStartFlyerProof and
 *    dispatch ADVANCE_TO_FLYER_PROOF instead.
 *
 * 7. OPTIONAL BACKEND: Store the flyer proof photo URL alongside the mission
 *    record in the database for owner verification in the vendor portal.
 *    The `previewDataUrl` passed to `onComplete` can be uploaded to S3 via
 *    the existing file upload pattern used in AssetVerification.
 *
 * ─── VISUAL NOTE ─────────────────────────────────────────────────────────────
 * The scanner denial state image (red octagon / SCAN REJECTED) generated by
 * ChatGPT should be used as the `deniedImageUrl` prop or imported as an asset.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { useState, useRef, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Camera, Check, MapPin, Navigation, XOctagon, RotateCw } from "lucide-react";
import type { GameMissionTarget } from "./driverGameTypes";
import { sounds } from "./driverSounds";
import { haptics } from "./driverHaptics";

interface Props {
  mission: GameMissionTarget;
  onComplete: (previewDataUrl?: string | null) => void;
}

export default function FlyerProofCapture({ mission, onComplete }: Props) {
  const [phase, setPhase] = useState<"prompt" | "scanning" | "confirmed" | "denied">("prompt");
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [showFlash, setShowFlash] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const previewUrlRef = useRef<string | null>(null);
  const [time, setTime] = useState("");

  useEffect(() => {
    const update = () =>
      setTime(new Date().toLocaleTimeString("en-US", { hour12: false }));
    update();
    const interval = setInterval(update, 1000);
    return () => clearInterval(interval);
  }, []);

  const processScan = useCallback(() => {
    setPhase("scanning");
    sounds.shutter();
    haptics.shutter();
    setShowFlash(true);
    setTimeout(() => setShowFlash(false), 150);

    setTimeout(() => {
      // PLACEHOLDER: Replace `denied` with real AI vision API result.
      // When vision model is wired, evaluate whether the photo shows a flyer
      // posted on a surface. If confidence < 0.7, set denied = true.
      const denied = false; // TODO: replace with: apiResult.confidence < 0.7

      if (denied) {
        setPhase("denied");
        sounds.overrideFail();
        haptics.error();
        setPreviewUrl(null);
        previewUrlRef.current = null;
        if (fileRef.current) fileRef.current.value = "";
      } else {
        setPhase("confirmed");
        sounds.scanConfirm();
        haptics.impact();
        setTimeout(() => {
          onComplete(previewUrlRef.current);
        }, 1200);
      }
    }, 1200);
  }, [onComplete]);

  const handleCapture = useCallback(() => {
    const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
    if (isMobile) {
      fileRef.current?.click();
    } else {
      // Desktop demo mode: skip real photo, proceed directly
      processScan();
    }
  }, [processScan]);

  const handleFileChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
      previewUrlRef.current = url;
      processScan();
    },
    [processScan]
  );

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen bg-black relative overflow-hidden flex flex-col"
    >
      <input
        ref={fileRef}
        type="file"
        accept="image/*"
        capture="environment"
        onChange={handleFileChange}
        className="hidden"
      />

      {/* Camera flash */}
      <AnimatePresence>
        {showFlash && (
          <motion.div
            initial={{ opacity: 1 }}
            animate={{ opacity: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="absolute inset-0 bg-white z-50"
          />
        )}
      </AnimatePresence>

      {/* SCAN REJECTED overlay */}
      <AnimatePresence>
        {phase === "denied" && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 z-40 flex flex-col items-center justify-center bg-black/95"
            style={{ boxShadow: "inset 0 0 80px rgba(255,34,68,0.2), inset 0 0 160px rgba(255,34,68,0.06)" }}
          >
            <div
              className="absolute inset-0 pointer-events-none opacity-[0.05]"
              style={{
                backgroundImage:
                  "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(255,34,68,0.3) 2px, rgba(255,34,68,0.3) 4px)",
              }}
            />
            <motion.div
              initial={{ scale: 0.5, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ type: "spring", damping: 10 }}
              className="mb-5"
            >
              <div
                className="w-20 h-20 border-2 border-danger/70 flex items-center justify-center mx-auto"
                style={{ clipPath: "polygon(30% 0%, 70% 0%, 100% 30%, 100% 70%, 70% 100%, 30% 100%, 0% 70%, 0% 30%)" }}
              >
                <XOctagon className="w-10 h-10 text-danger" />
              </div>
            </motion.div>
            <p className="text-[9px] tracking-[0.5em] text-danger uppercase font-semibold mb-2">
              Proof Rejected
            </p>
            <p className="font-display font-extrabold text-3xl uppercase tracking-wider text-danger mb-3">
              Image Denied
            </p>
            <p className="text-[10px] text-muted-foreground text-center max-w-[220px] leading-relaxed mb-8">
              Flyer not visible in frame — retake required.
            </p>
            <button
              onClick={() => setPhase("prompt")}
              className="flex items-center gap-2.5 border border-danger/50 hover:border-danger
                         px-8 py-3 transition-all active:bg-danger/10"
            >
              <RotateCw className="w-4 h-4 text-danger" />
              <span className="font-display font-bold text-base uppercase tracking-wider text-danger">
                Retake
              </span>
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Confirmed overlay */}
      <AnimatePresence>
        {phase === "confirmed" && (
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 z-40 flex items-center justify-center"
          >
            <div className="text-center">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", damping: 8 }}
                className="w-20 h-20 border-2 border-neon mx-auto mb-4 flex items-center justify-center"
              >
                <Check className="w-10 h-10 text-neon" />
              </motion.div>
              <p className="text-[10px] tracking-[0.4em] text-neon uppercase font-semibold">
                Proof Captured
              </p>
              <p className="text-[9px] text-muted-foreground mt-1 tracking-wider">
                Initiating Signal Override…
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header */}
      <div className="relative z-10 px-4 pt-4 pb-2">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-[8px] tracking-[0.4em] text-neon/50 uppercase">
              Flyer Proof
            </p>
            <p className="text-[10px] text-muted-foreground mt-0.5">
              Capture posted flyer to unlock override
            </p>
          </div>
          <span className="text-[9px] text-neon/40 font-mono">{time}</span>
        </div>
      </div>

      {/* Mission context */}
      <div className="px-4 py-2 border-t border-border/10 border-b border-border/10">
        <div className="flex items-start gap-2">
          <MapPin className="w-3.5 h-3.5 text-neon/50 mt-0.5 shrink-0" />
          <div>
            <p className="text-[9px] tracking-[0.15em] text-neon/70 uppercase font-semibold">
              {mission.label}
            </p>
            {mission.address && (
              <p className="text-[9px] text-muted-foreground mt-0.5">
                {mission.address}
              </p>
            )}
          </div>
          {mission.mapsUrl && (
            <a
              href={mission.mapsUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="ml-auto flex items-center gap-1 text-[8px] text-neon/50 hover:text-neon transition-colors"
            >
              <Navigation className="w-3 h-3" />
              <span className="tracking-wider uppercase">Nav</span>
            </a>
          )}
        </div>
      </div>

      {/* Viewfinder */}
      <div className="flex-1 relative mx-4 my-3 border border-neon/15 overflow-hidden bg-void-light/50">
        {previewUrl && (
          <img
            src={previewUrl}
            alt="Flyer proof preview"
            className="absolute inset-0 w-full h-full object-cover"
          />
        )}

        {/* Crosshair overlay */}
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <div className="absolute left-0 right-0 h-px bg-neon/15" />
          <div className="absolute top-0 bottom-0 w-px bg-neon/15" />
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
            className="w-16 h-16 border border-neon/30"
            style={{ clipPath: "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)" }}
          />
          <div className="absolute w-6 h-6 border border-neon/50" />
          <div className="absolute w-1 h-1 bg-neon" />
        </div>

        {/* Corner brackets */}
        <div className="absolute top-3 left-3 w-8 h-8 border-t-2 border-l-2 border-neon/50" />
        <div className="absolute top-3 right-3 w-8 h-8 border-t-2 border-r-2 border-neon/50" />
        <div className="absolute bottom-3 left-3 w-8 h-8 border-b-2 border-l-2 border-neon/50" />
        <div className="absolute bottom-3 right-3 w-8 h-8 border-b-2 border-r-2 border-neon/50" />

        {/* Scan line */}
        {phase === "scanning" && (
          <motion.div
            initial={{ top: "0%" }}
            animate={{ top: "100%" }}
            transition={{ duration: 0.9, ease: "linear" }}
            className="absolute left-0 right-0 h-0.5 bg-neon shadow-[0_0_16px_oklch(0.85_0.25_155),0_0_4px_oklch(0.85_0.25_155)]"
          />
        )}

        {/* Status readout */}
        <div className="absolute bottom-3 left-3 right-3 flex justify-between items-end pointer-events-none">
          <p className="text-[7px] text-neon/40 tracking-wider font-mono">
            FLYER SCAN
          </p>
          <p className={`text-[7px] tracking-wider font-mono ${
            phase === "scanning" ? "text-amber animate-pulse" : "text-neon/40"
          }`}>
            {phase === "scanning" ? "PROCESSING..." : "READY"}
          </p>
        </div>
      </div>

      {/* Instructions */}
      <div className="px-4 py-2 text-center">
        <p className="font-display font-extrabold text-xl uppercase tracking-wider text-foreground">
          Flyer Proof
        </p>
        <p className="text-[10px] text-muted-foreground mt-1">
          Point camera at posted flyer — confirm placement
        </p>
      </div>

      {/* CTA */}
      <div className="px-4 pb-8 pt-2">
        <button
          onClick={handleCapture}
          disabled={phase === "scanning" || phase === "confirmed"}
          className="w-full py-4 border-2 border-neon/80 flex items-center justify-center gap-3
                     active:bg-neon/10 transition-all disabled:opacity-30 disabled:border-neon/20
                     hover:shadow-[0_0_16px_oklch(0.85_0.25_155/0.2)]"
        >
          <Camera className="w-5 h-5 text-neon" />
          <span className="font-display font-extrabold text-lg uppercase tracking-wider text-neon">
            {phase === "scanning" ? "Scanning..." : phase === "confirmed" ? "Confirmed" : "Capture Proof"}
          </span>
        </button>
      </div>
    </motion.div>
  );
}
