export const RALLY_CONFIG = {
  arena: {
    width: 1200,
    height: 650,
    cornerLeg: 140,
    gateTop: 260,
    gateBottom: 420,
    gateThreatDistance: 350,
    wallRestitution: 0.98,
    bumperRestitution: 1.04,
    bumperJitterDegrees: 3,
    gatePostRadius: 13,
  },
  simulation: {
    fixedHz: 120,
    maxFrameMs: 100,
    seed: 0x5eedc0de,
  },
  excuse: {
    radius: 31,
    serveSpeed: 340,
    returnMultiplier: 1.06,
    maxSpeed: 980,
    bodyDamping: 0.9,
    continuousCollisionSpeed: 800,
    contactLockMs: 100,
    speedTiers: [0, 460, 650, 800] as const,
    trailPoints: 28,
    igniteMs: 2500,
  },
  spark: {
    spawnX: 255,
    spawnY: 340,
    radius: 48,
    minX: 70,
    maxX: 560,
    minY: 120,
    maxY: 520,
    moveSpeed: 305,
    energyMax: 100,
    energyRegenPerSecond: 15,
    breathRange: 220,
    breathHalfAngleDegrees: 40,
    breathAcceleration: 1400,
    breathEnergyPerSecond: 22,
    chargedBreathMs: 800,
    breathAnticipationMs: 120,
    breathEventIntervalMs: 90,
    breathExhaustedThreshold: 8,
    breathContactEventIntervalMs: 80,
    chargedBreathForceMultiplier: 1.24,
    chargedBreathWidthMultiplier: 1.18,
    mouthOffset: 48,
    dashDistance: 135,
    dashDeflectRange: 60,
    dashDeflectMultiplier: 1.08,
    dashDurationMs: 180,
    dashInvulnerabilityMs: 360,
    dashCooldownMs: 950,
    dashEnergyCost: 16,
    freezeMs: 1400,
  },
  clockhead: {
    spawnX: 945,
    spawnY: 330,
    radius: 52,
    minX: 640,
    maxX: 1130,
    minY: 130,
    maxY: 515,
    moveSpeed: 260,
    reactionDelayMs: { tier0: 220, tier3: 120 },
    whiffChance: 0.08,
    whiffRecoveryMs: 520,
    swatTelegraphMs: 450,
    swatRadius: 205,
    swatMultiplier: 1.1,
    freezeTelegraphMs: 700,
    freezeCooldownMs: 12000,
    scriptedFreezeRally: 5,
    staggerMs: 600,
  },
  scoring: {
    mode: "buttHybrid" as "portal" | "buttHybrid",
    winScore: 5,
    regulationMs: 90000,
    firstServeSlowMs: 1500,
    firstServeTimeScale: 0.5,
    resetMs: 1200,
    influencePerReturn: 6,
    influenceOnScore: 14,
    influenceWhenScoredOn: -14,
    startingInfluence: 50,
  },
  buttTarget: {
    offset: 46,
    radius: 36,
    wallInset: 0,
    springStiffness: 90,
    springDamping: 12,
    highSpeedSubstepThreshold: 620,
    clockheadExposureMs: 350,
    tieEpsilon: 0.0001,
    tutorialPulseRadius: 58,
  },
  ceremony: {
    ingestionMs: 220,
    hitStopMs: 90,
    reactionMs: 450,
    bannerMs: 650,
    beatMs: 1200,
    serveTelegraphMs: 900,
    ingestionTurns: 1.35,
    ingestionSquash: 0.42,
    ingestionMinScale: 0.05,
    impactParticleMin: 40,
    impactParticleMax: 60,
    bannerTiltDegrees: 4,
    bannerOvershoot: 1.08,
  },
  fire: {
    particleBudget: 80,
    coreWidth: 15,
    bodyWidth: 42,
    emberCount: 18,
    smokeCount: 8,
    mouthGlowRadius: 34,
    contactSplashRadius: 44,
    exhaustedPuffCount: 5,
  },
  feel: {
    returnHitStopMs: 45,
    bumperHitStopMs: 60,
    scoreHitStopMs: 90,
    traumaReturn: 0.2,
    traumaBank: 0.25,
    traumaScore: 0.55,
    traumaDecayPerSecond: 1.8,
    particleCap: 200,
    reducedMotionParticleCap: 40,
    maxStretch: 1.25,
    minSquash: 0.8,
  },
  rescue: {
    acceptWindowMs: 20000,
    returnForceMultiplier: 3,
  },
  haptics: {
    returnMs: 20,
    scoreMs: 60,
  },
} as const;

export const FIXED_STEP_MS = 1000 / RALLY_CONFIG.simulation.fixedHz;

export type RallyConfig = typeof RALLY_CONFIG;
