import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  buildOperatorContextPacket,
  MINIMUM_PATTERN_INDEPENDENT_OBSERVATIONS,
  type OperatorContextDeps,
  type OperatorContextPacket,
} from "./operatorContext";
import type { CanonicalOperatorIdentity } from "./identity";
import type { BoundedLedgerReadEvent } from "../behavioralLedger/behavioralLedger";
import type { GoalCycleLearnedDeltaRecord } from "./learningStore";
import { DIAGNOSIS_FORBIDDEN_PATTERNS } from "../../shared/behavioralInterventionMapping";
import type { GoldlineOnboardingSession } from "../../shared/goldlineOnboarding";

// ---------------------------------------------------------------------------
// Test Fixtures (Pure In-Memory / Disposable / Zero Live DB Calls)
// ---------------------------------------------------------------------------

function makeCanonicalIdentity(overrides: Partial<CanonicalOperatorIdentity> = {}): CanonicalOperatorIdentity {
  return {
    tenantId: "tenant_alpha",
    canonicalOperatorId: "tenant:tenant_alpha:operator:alice_main",
    canonicalOpenId: "alice_main",
    canonicalUserId: 101,
    sourceOpenId: "alice_main",
    sourceUserId: 101,
    sourceRole: "admin",
    dayDirectorActorId: "101",
    dayDirectorActorIds: ["101", "102"],
    weeklyOperatorId: "alice_main",
    campaignOperatorUserId: "alice_main",
    communicationOperatorUserId: "alice_main",
    membership: { source: "owner", canonical: "owner" },
    aliases: [
      { openId: "alice_main", userId: 101, role: "admin", surface: "admin" },
      { openId: "alice_field", userId: 102, role: "driver", surface: "driver" },
    ],
    ...overrides,
  };
}

function makeLedgerEvent(overrides: Partial<BoundedLedgerReadEvent> = {}): BoundedLedgerReadEvent {
  return {
    id: 1,
    tenantId: "tenant_alpha",
    operatorUserId: "101",
    correlationId: "ops_task:task_1",
    sourceSystem: "ops_task",
    sourceEntityType: "ops_task_event",
    sourceEntityId: "event_1",
    eventType: "DELIVERED",
    occurredAt: new Date("2026-10-01T14:00:00Z"),
    verificationClass: null,
    provenance: "server_event",
    evidenceSource: null,
    decisionPointId: "dp_1",
    availability: true,
    eligibleOptionsJson: ["option_a", "option_b"],
    assignedOption: "option_a",
    assignmentProbability: "0.50000",
    interventionPolicyVersion: 1,
    interventionDefinitionVersion: 1,
    proximalOutcomeWindowMinutes: 60,
    idempotencyKey: "idem_1",
    ...overrides,
  };
}

function makeLearnedDelta(overrides: Partial<GoalCycleLearnedDeltaRecord> = {}): GoalCycleLearnedDeltaRecord {
  return {
    id: "delta_1",
    tenantId: "tenant_alpha",
    goalRunId: "run_1",
    cycleId: "cycle_1",
    decisionId: "dec_1",
    objectiveId: "obj_1",
    outcomeId: "out_1",
    canonicalOperatorId: "tenant:tenant_alpha:operator:alice_main",
    operatorUserId: "101",
    learningKind: "time_preference",
    targetKey: "sales:morning_block",
    deltaType: "boost",
    beforeState: { morningWeight: 1.0 },
    afterState: { morningWeight: 1.2, verifiedDeliveries: 3 },
    evidenceReference: "commercial_attributions:123",
    confidence: "medium",
    explanation: "Deterministic delta explanation generated by learningStore.",
    appliedCount: 1,
    createdAt: "2026-09-30T10:00:00.000Z",
    updatedAt: "2026-09-30T10:00:00.000Z",
    ...overrides,
  };
}

describe("Stage 1 JOYSTICK Operator Context", () => {
  // -------------------------------------------------------------------------
  // 1. Identity & Isolation
  // -------------------------------------------------------------------------
  describe("Identity & Tenant Isolation", () => {
    it("requires authorized tenant and operator scope", async () => {
      await expect(
        buildOperatorContextPacket({
          tenantId: "",
          canonicalOperatorId: "tenant:t1:operator:op1",
        })
      ).rejects.toThrow("tenantId is required");
    });

    it("rejects when identity tenant does not match input tenant", async () => {
      const identity = makeCanonicalIdentity({ tenantId: "tenant_alpha" });
      await expect(
        buildOperatorContextPacket({
          tenantId: "tenant_beta",
          identity,
        })
      ).rejects.toThrow("belongs to tenant 'tenant_alpha', not requested tenant 'tenant_beta'");
    });

    it("ensures Tenant A never queries Tenant B evidence", async () => {
      let queriedTenant = "";
      const deps: OperatorContextDeps = {
        loadLedgerEvents: async ({ tenantId }) => {
          queriedTenant = tenantId;
          return [];
        },
      };

      const identity = makeCanonicalIdentity({ tenantId: "tenant_alpha" });
      await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity,
        deps,
      });

      expect(queriedTenant).toBe("tenant_alpha");
    });

    it("ensures queries use mapped operatorUserId values, not canonicalOperatorId", async () => {
      let queriedUserIds: string[] = [];
      const deps: OperatorContextDeps = {
        loadLedgerEvents: async ({ operatorUserIds }) => {
          queriedUserIds = operatorUserIds;
          return [];
        },
      };

      const identity = makeCanonicalIdentity({
        canonicalOperatorId: "tenant:tenant_alpha:operator:alice_main",
        canonicalUserId: 101,
        sourceUserId: 101,
        aliases: [
          { openId: "alice_main", userId: 101, role: "admin", surface: "admin" },
          { openId: "alice_field", userId: 102, role: "driver", surface: "driver" },
        ],
      });

      await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity,
        deps,
      });

      // Mapped user IDs: 101 and 102
      expect(queriedUserIds).toContain("101");
      expect(queriedUserIds).toContain("102");
      expect(queriedUserIds).not.toContain("tenant:tenant_alpha:operator:alice_main");
    });

    it("restricts queried user IDs strictly to mapped users, never broadening to the whole tenant", async () => {
      let queriedUserIds: string[] = [];
      const deps: OperatorContextDeps = {
        loadLedgerEvents: async ({ operatorUserIds }) => {
          queriedUserIds = operatorUserIds;
          return [];
        },
      };

      const identity = makeCanonicalIdentity({
        canonicalUserId: 101,
        aliases: [{ openId: "alice_main", userId: 101, role: "admin", surface: "admin" }],
      });

      await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity,
        deps,
      });

      expect(queriedUserIds).toEqual(["101"]);
    });

    it("preserves canonical-to-user-ID mapping in evidence references", async () => {
      const identity = makeCanonicalIdentity({
        canonicalUserId: 101,
        aliases: [{ openId: "alice_alias", userId: 102, role: "driver", surface: "driver" }],
      });

      const deps: OperatorContextDeps = {
        loadLedgerEvents: async () => [
          makeLedgerEvent({ id: 55, operatorUserId: "102" }),
        ],
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity,
        deps,
      });

      const ledgerRef = packet.evidenceRefs.find(r => r.sourceRecordId === "55");
      expect(ledgerRef).toBeDefined();
      expect(ledgerRef?.operatorUserId).toBe("102");
      expect(ledgerRef?.canonicalOperatorId).toBe("tenant:tenant_alpha:operator:alice_main");
    });
  });

  // -------------------------------------------------------------------------
  // 2. Explicit Information & The Three Acquisition Answers
  // -------------------------------------------------------------------------
  describe("Explicit Information Boundaries", () => {
    it("surfaces declared acquisition facts conservatively without transforming them into preferences when bound", async () => {
      const session: GoldlineOnboardingSession & { operatorUserId?: string } = {
        id: "sess_1",
        tenantId: "tenant_alpha",
        status: "READY",
        currentQuestion: 3,
        answers: ["Residential plumbing", "Pasadena, CA", "Calling cold leads"],
        answersByKey: {
          daily_work: "Residential plumbing",
          service_area: "Pasadena, CA",
          avoidance: "Calling cold leads",
        },
        operatorUserId: "101",
        startedAt: "2026-10-01T10:00:00Z",
        completedAt: null,
        version: 1,
        acquisitionSessionId: null,
        interpretation: null,
        optionalUploadReference: null,
        world: null,
        mission: null,
      };

      const deps: OperatorContextDeps = {
        loadOnboardingSession: async () => session,
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps,
      });

      const tradeFact = packet.card.explicitFacts.find(f => f.kind === "declared_trade");
      const areaFact = packet.card.explicitFacts.find(f => f.kind === "declared_service_area");
      const avoidanceFact = packet.card.explicitFacts.find(f => f.kind === "declared_avoided_task");

      expect(tradeFact?.statement).toContain("Residential plumbing");
      expect(areaFact?.statement).toContain("Pasadena, CA");
      expect(avoidanceFact?.statement).toBe('Declared avoided task: "Calling cold leads"');

      // MUST NOT be transformed into contact preference or psychological diagnosis
      expect(packet.card.explicitPreferences).toHaveLength(0);
      const json = JSON.stringify(packet);
      expect(json).not.toContain("morning_person");
      expect(json).not.toContain("avoidant");
      expect(json).not.toContain("phone_preference");
    });

    it("omits tenant-scoped onboarding facts when authoritative operator binding is absent and emits operator_binding_unavailable", async () => {
      const session: GoldlineOnboardingSession = {
        id: "sess_tenant_only",
        tenantId: "tenant_alpha",
        status: "READY",
        currentQuestion: 3,
        answers: ["Electrical", "Glendale, CA", "Filing taxes"],
        answersByKey: {
          daily_work: "Electrical",
          service_area: "Glendale, CA",
          avoidance: "Filing taxes",
        },
        startedAt: "2026-10-01T10:00:00Z",
        completedAt: null,
        version: 1,
        acquisitionSessionId: null,
        interpretation: null,
        optionalUploadReference: null,
        world: null,
        mission: null,
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadOnboardingSession: async () => session },
      });

      // Tenant onboarding facts are omitted from operator card
      expect(packet.card.explicitFacts.filter(f => f.kind !== "canonical_identity")).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "operator_binding_unavailable")).toBe(true);
    });

    it("does not classify free text into structured preference fields", async () => {
      const session: GoldlineOnboardingSession & { operatorUserId?: string } = {
        id: "sess_2",
        tenantId: "tenant_alpha",
        status: "READY",
        currentQuestion: 3,
        answers: ["General contracting", "Downtown", "Hate early morning calls"],
        answersByKey: {
          daily_work: "General contracting",
          service_area: "Downtown",
          avoidance: "Hate early morning calls",
        },
        operatorUserId: "101",
        startedAt: "2026-10-01T10:00:00Z",
        completedAt: null,
        version: 1,
        acquisitionSessionId: null,
        interpretation: null,
        optionalUploadReference: null,
        world: null,
        mission: null,
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadOnboardingSession: async () => session },
      });

      // Avoidance text "Hate early morning calls" must remain an explicit declared avoided task fact,
      // NOT classified into morningPreference or contactMethod.
      expect(packet.card.explicitPreferences).toHaveLength(0);
      expect(packet.card.explicitFacts.some(f => f.kind === "declared_avoided_task")).toBe(true);
      const fact = packet.card.explicitFacts.find(f => f.kind === "declared_avoided_task");
      expect(fact?.statement).toBe('Declared avoided task: "Hate early morning calls"');
    });

    it("never manufactures a fake placeholder card fact when no preference exists", async () => {
      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadLedgerEvents: async () => [],
          loadLearnedDeltas: async () => [],
          loadOnboardingSession: async () => null,
        },
      });

      expect(packet.card.explicitPreferences).toHaveLength(0);
      expect(
        packet.card.explicitFacts.some(f =>
          f.statement.includes("No contact preference known")
        )
      ).toBe(false);
    });

    it("does not turn one explicit statement into an observed behavioral pattern", async () => {
      const session: GoldlineOnboardingSession & { operatorUserId?: string } = {
        id: "sess_3",
        tenantId: "tenant_alpha",
        status: "READY",
        currentQuestion: 1,
        answers: ["Welding"],
        answersByKey: { daily_work: "Welding" },
        operatorUserId: "101",
        startedAt: "2026-10-01T10:00:00Z",
        completedAt: null,
        version: 1,
        acquisitionSessionId: null,
        interpretation: null,
        optionalUploadReference: null,
        world: null,
        mission: null,
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadOnboardingSession: async () => session },
      });

      expect(packet.observedPatterns).toHaveLength(0);
    });
  });

  // -------------------------------------------------------------------------
  // 3. Behavioral Independence & Pattern Threshold (3 Independent Observations)
  // -------------------------------------------------------------------------
  describe("Behavioral Independence & Pattern Thresholds", () => {
    it("does not emit an observed pattern with 1 decision point", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 2, decisionPointId: "dp_1", eventType: "STARTED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "insufficient_observations")).toBe(true);
    });

    it("does not emit an observed pattern with 2 distinct decision points", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 2, decisionPointId: "dp_1", eventType: "STARTED" }),
        makeLedgerEvent({ id: 3, decisionPointId: "dp_2", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 4, decisionPointId: "dp_2", eventType: "STARTED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "insufficient_observations")).toBe(true);
    });

    it("treats DELIVERED, ENGAGED, STARTED sharing one decisionPointId as ONE observation", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 2, decisionPointId: "dp_1", eventType: "ENGAGED" }),
        makeLedgerEvent({ id: 3, decisionPointId: "dp_1", eventType: "STARTED" }),
        makeLedgerEvent({ id: 4, decisionPointId: "dp_1", eventType: "COMPLETED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // 4 rows sharing 1 decision point = 1 observation, NOT 4!
      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "insufficient_observations")).toBe(true);
    });

    it("emits a descriptive pattern when 3 distinct qualifying decision points exist", async () => {
      const baseTime = new Date("2026-10-01T10:00:00Z").getTime();
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_1",
          correlationId: "ops_task:1",
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime),
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_1",
          correlationId: "ops_task:1",
          eventType: "STARTED",
          occurredAt: new Date(baseTime + 300_000),
        }),
        makeLedgerEvent({
          id: 3,
          decisionPointId: "dp_2",
          correlationId: "ops_task:2",
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime + 3600_000),
        }),
        makeLedgerEvent({
          id: 4,
          decisionPointId: "dp_2",
          correlationId: "ops_task:2",
          eventType: "STARTED",
          occurredAt: new Date(baseTime + 3900_000),
        }),
        makeLedgerEvent({
          id: 5,
          decisionPointId: "dp_3",
          correlationId: "ops_task:3",
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime + 7200_000),
        }),
        makeLedgerEvent({
          id: 6,
          decisionPointId: "dp_3",
          correlationId: "ops_task:3",
          eventType: "STARTED",
          occurredAt: new Date(baseTime + 7500_000),
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      expect(packet.observedPatterns.length).toBeGreaterThanOrEqual(1);
      const pattern = packet.observedPatterns[0]!;
      expect(pattern.observationCount).toBe(3);
      expect(pattern.distinctDecisionPointCount).toBe(3);
      expect(pattern.confidence).toBe("descriptive");
      expect(pattern.summary).toContain("3 of 3 qualifying decision points were followed by a STARTED event");
    });

    it("maintains distinct meanings for DISMISSED, DEFERRED, NOT_COMPLETED, EXPIRED, and SUPERSEDED", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1", eventType: "DEFERRED" }),
        makeLedgerEvent({ id: 2, decisionPointId: "dp_2", eventType: "DISMISSED" }),
        makeLedgerEvent({ id: 3, decisionPointId: "dp_3", eventType: "NOT_COMPLETED" }),
        makeLedgerEvent({ id: 4, decisionPointId: "dp_4", eventType: "EXPIRED" }),
        makeLedgerEvent({ id: 5, decisionPointId: "dp_5", eventType: "SUPERSEDED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // Verify that event types are kept distinct and never collapsed into "avoidance"
      const json = JSON.stringify(packet);
      expect(json).not.toContain("avoidant");
      expect(json).not.toContain("lazy");
      expect(json).not.toContain("ignored");
    });

    it("does not count decision points with missing outcome window toward qualifying pattern threshold", async () => {
      const baseTime = new Date("2026-10-01T10:00:00Z").getTime();
      const events: BoundedLedgerReadEvent[] = [1, 2, 3].flatMap(i => [
        makeLedgerEvent({
          id: i * 2 - 1,
          decisionPointId: `dp_${i}`,
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime + i * 3600_000),
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: null, // missing window!
        }),
        makeLedgerEvent({
          id: i * 2,
          decisionPointId: `dp_${i}`,
          eventType: "STARTED",
          occurredAt: new Date(baseTime + i * 3600_000 + 60_000),
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: null,
        }),
      ]);

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // Because proximalOutcomeWindowMinutes is missing, none qualify for start-window sequence pattern
      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "proximal_outcome_window_unavailable")).toBe(true);
    });

    it("does not count decision points with STARTED predating assignment toward pattern startedInWindow", async () => {
      const baseTime = new Date("2026-10-01T10:00:00Z").getTime();
      // 3 qualifying decision points, but in all 3 the STARTED occurred BEFORE assignment
      const events: BoundedLedgerReadEvent[] = [1, 2, 3].flatMap(i => [
        makeLedgerEvent({
          id: i * 2 - 1,
          decisionPointId: `dp_${i}`,
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime + i * 3600_000),
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: 60,
        }),
        makeLedgerEvent({
          id: i * 2,
          decisionPointId: `dp_${i}`,
          eventType: "STARTED",
          occurredAt: new Date(baseTime + i * 3600_000 - 30_000), // 30s before presentation!
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: 60,
        }),
      ]);

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // Pattern is derived over qualifying decision points
      expect(packet.observedPatterns).toHaveLength(1);
      const pattern = packet.observedPatterns[0]!;
      expect(pattern.metrics?.startedWithinWindowCount).toBe(0); // 0 of 3 started in window!
      expect(pattern.metrics?.startedLatencyMeanSeconds).toBeNull(); // latency was not clamped to 0
      expect(pattern.summary).toContain("0 of 3 qualifying decision points were followed by a STARTED event");
      expect(packet.uncertainty.some(u => u.reason === "invalid_temporal_evidence")).toBe(true);
    });
  });

  // -------------------------------------------------------------------------
  // 4. Ledger Query Safety & Bounded Reads
  // -------------------------------------------------------------------------
  describe("Ledger Query Safety", () => {
    it("enforces explicit bound on ledger reads and safe failure if query fails", async () => {
      let requestedLimit = 0;
      const deps: OperatorContextDeps = {
        loadLedgerEvents: async ({ limit }) => {
          requestedLimit = limit;
          throw new Error("Connection timeout");
        },
        loadLearnedDeltas: async () => [],
        loadOnboardingSession: async () => null,
      };

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps,
      });

      expect(requestedLimit).toBeGreaterThan(0);
      expect(requestedLimit).toBeLessThanOrEqual(500);
      // 1. ledger loader failure emits source_unavailable
      expect(packet.uncertainty.some(u => u.reason === "source_unavailable" && u.scope === "behavioral_ledger")).toBe(true);
      // 2. ledger loader failure does NOT emit no_records
      expect(packet.uncertainty.some(u => u.reason === "no_records")).toBe(false);
      // 3. ledger loader failure does NOT emit no_verified_outcome
      expect(packet.uncertainty.some(u => u.reason === "no_verified_outcome")).toBe(false);
    });
  });

  // -------------------------------------------------------------------------
  // 5. Timing, Latency, and Timezone Discipline
  // -------------------------------------------------------------------------
  describe("Timing & Timezone Discipline", () => {
    it("calculates start latency only when paired presentation and start timestamps exist", async () => {
      const base = new Date("2026-10-01T12:00:00Z");
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_1",
          eventType: "DELIVERED",
          occurredAt: base,
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_1",
          eventType: "STARTED",
          occurredAt: new Date(base.getTime() + 120_000), // 120 seconds later
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const intervention = packet.interventionEvidence.find(ie => ie.decisionPointId === "dp_1");
      expect(intervention?.startLatencySeconds).toBe(120);
      expect(intervention?.startedWithinWindow).toBe(true);
    });

    it("marks startedWithinWindow as unknown and startLatencySeconds as null when proximalOutcomeWindowMinutes is missing", async () => {
      const base = new Date("2026-10-01T12:00:00Z");
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_1",
          eventType: "DELIVERED",
          occurredAt: base,
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: null,
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_1",
          eventType: "STARTED",
          occurredAt: new Date(base.getTime() + 120_000),
          proximalOutcomeWindowMinutes: null,
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const intervention = packet.interventionEvidence.find(ie => ie.decisionPointId === "dp_1");
      expect(intervention?.startedWithinWindow).toBe("unknown");
      expect(intervention?.startLatencySeconds).toBeNull();
      expect(intervention?.outcomeWindowMinutes).toBeNull();
      expect(packet.uncertainty.some(u => u.reason === "proximal_outcome_window_unavailable")).toBe(true);
    });

    it("does not treat non-assignment lifecycle events as assignment when assignedOption is absent", async () => {
      const base = new Date("2026-10-01T12:00:00Z");
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_1",
          eventType: "DELIVERED",
          occurredAt: base,
          assignedOption: null,
          proximalOutcomeWindowMinutes: null,
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_1",
          eventType: "STARTED",
          occurredAt: new Date(base.getTime() + 120_000),
          assignedOption: null,
          proximalOutcomeWindowMinutes: null,
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const intervention = packet.interventionEvidence.find(ie => ie.decisionPointId === "dp_1");
      expect(intervention?.assignedOption).toBeNull();
      expect(intervention?.startedWithinWindow).toBe("unknown");
      expect(intervention?.startLatencySeconds).toBeNull();
      expect(packet.uncertainty.some(u => u.reason === "missing_paired_timestamps")).toBe(true);
    });

    it("rejects STARTED events that predate assignment without clamping negative latency to zero", async () => {
      const base = new Date("2026-10-01T12:00:00Z");
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_1",
          eventType: "STARTED",
          occurredAt: new Date(base.getTime() - 60_000), // 60s BEFORE assignment!
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: 60,
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_1",
          eventType: "DELIVERED",
          occurredAt: base,
          assignedOption: "option_a",
          proximalOutcomeWindowMinutes: 60,
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const intervention = packet.interventionEvidence.find(ie => ie.decisionPointId === "dp_1");
      expect(intervention?.startedWithinWindow).not.toBe(true);
      expect(intervention?.startedWithinWindow).toBe(false);
      expect(intervention?.startLatencySeconds).toBeNull(); // NOT clamped to 0!
      expect(packet.uncertainty.some(u => u.reason === "invalid_temporal_evidence")).toBe(true);
    });

    it("emits timezone_unavailable when authoritative timezone is absent", async () => {
      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadTenantTimezone: async () => null,
        },
      });

      expect(packet.uncertainty.some(u => u.reason === "timezone_unavailable")).toBe(true);
      const json = JSON.stringify(packet);
      expect(json).not.toContain("morning_person");
      expect(json).not.toContain("before 10:00 AM");
    });
  });

  // -------------------------------------------------------------------------
  // 6. Existing Learned Deltas
  // -------------------------------------------------------------------------
  describe("Surfacing Existing Learned Deltas", () => {
    it("normalizes existing goalCycleLearnedDeltas without leaking generated prose into Claire", async () => {
      const delta = makeLearnedDelta({
        learningKind: "time_preference",
        targetKey: "time:early_morning",
        confidence: "medium",
        explanation: "DO NOT REPEAT THIS PROSE TO CLAIRE",
      });

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLearnedDeltas: async () => [delta] },
      });

      expect(packet.learnedSignals).toHaveLength(1);
      const signal = packet.learnedSignals[0]!;
      expect(signal.learningKind).toBe("time_preference");
      expect(signal.targetKey).toBe("time:early_morning");
      expect(signal.confidence).toBe("medium");
      expect(signal.deltaType).toBe("boost");

      // The explanation prose MUST NOT be placed on the signal
      expect((signal as any).explanation).toBeUndefined();
    });

    it("reflects source deletion on rebuild (ephemeral read model)", async () => {
      let deltas: GoalCycleLearnedDeltaRecord[] = [makeLearnedDelta({ id: "d1" })];

      const deps: OperatorContextDeps = {
        loadLearnedDeltas: async () => deltas,
      };

      const packet1 = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps,
      });
      expect(packet1.learnedSignals).toHaveLength(1);

      // Simulate deletion in source store
      deltas = [];

      const packet2 = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps,
      });
      expect(packet2.learnedSignals).toHaveLength(0);
    });
  });

  // -------------------------------------------------------------------------
  // 7. Causal Discipline & Forbidden Phrasing
  // -------------------------------------------------------------------------
  describe("Causal Discipline & Forbidden Diagnosis Patterns", () => {
    it("does not emit causal claims from observational sequences", async () => {
      const baseTime = new Date("2026-10-01T10:00:00Z").getTime();
      const events: BoundedLedgerReadEvent[] = [1, 2, 3].flatMap(i => [
        makeLedgerEvent({
          id: i * 2 - 1,
          decisionPointId: `dp_${i}`,
          eventType: "DELIVERED",
          occurredAt: new Date(baseTime + i * 3600_000),
          assignedOption: "option_a",
          assignmentProbability: null, // observational
        }),
        makeLedgerEvent({
          id: i * 2,
          decisionPointId: `dp_${i}`,
          eventType: "STARTED",
          occurredAt: new Date(baseTime + i * 3600_000 + 60_000),
          assignedOption: "option_a",
        }),
      ]);

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const serialized = JSON.stringify(packet);
      for (const pattern of DIAGNOSIS_FORBIDDEN_PATTERNS) {
        expect(pattern.test(serialized)).toBe(false);
      }
    });

    it("marks observational interventions as descriptive and preserves randomized probabilities", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({
          id: 1,
          decisionPointId: "dp_random",
          eventType: "DELIVERED",
          assignmentProbability: "0.33333",
        }),
        makeLedgerEvent({
          id: 2,
          decisionPointId: "dp_obs",
          eventType: "DELIVERED",
          assignmentProbability: null,
        }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const randomEvidence = packet.interventionEvidence.find(e => e.decisionPointId === "dp_random");
      const obsEvidence = packet.interventionEvidence.find(e => e.decisionPointId === "dp_obs");

      expect(randomEvidence?.assignmentMechanism).toBe("randomized_assignment");
      expect(randomEvidence?.assignmentProbability).toBe(0.33333);
      expect(obsEvidence?.assignmentMechanism).toBe("deterministic_or_observational");
      expect(obsEvidence?.assignmentProbability).toBeNull();
      expect(randomEvidence?.isDescriptiveOnly).toBe(true);
      expect(obsEvidence?.isDescriptiveOnly).toBe(true);
    });
  });

  // -------------------------------------------------------------------------
  // 8. Conflict & Empty State Behavior
  // -------------------------------------------------------------------------
  describe("Uncertainty & Empty State", () => {
    it("successful ledger read returning [], successful learned-delta read returning [], and successful onboarding read returning null may emit no_records", async () => {
      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadLedgerEvents: async () => [],
          loadLearnedDeltas: async () => [],
          loadOnboardingSession: async () => null,
        },
      });

      expect(packet.card.explicitPreferences).toHaveLength(0);
      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.learnedSignals).toHaveLength(0);
      expect(packet.interventionEvidence).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "no_records")).toBe(true);
      expect(packet.uncertainty.some(u => u.reason === "source_unavailable")).toBe(false);
    });

    it("onboarding loader failure emits source_unavailable rather than being treated as no session and suppresses no_records", async () => {
      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadLedgerEvents: async () => [],
          loadLearnedDeltas: async () => [],
          loadOnboardingSession: async () => {
            throw new Error("Onboarding store connection failure");
          },
        },
      });

      expect(packet.uncertainty.some(u => u.reason === "source_unavailable" && u.scope === "goldline_onboarding")).toBe(true);
      expect(packet.uncertainty.some(u => u.reason === "no_records")).toBe(false);
    });

    it("emits no_verified_outcome with bounded evidence wording when no verified events or receipts exist", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, eventType: "DELIVERED", verificationClass: null }),
        makeLedgerEvent({ id: 2, eventType: "STARTED", verificationClass: null }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const uncert = packet.uncertainty.find(u => u.reason === "no_verified_outcome");
      expect(uncert).toBeDefined();
      expect(uncert?.detail).toBe(
        "No verified action or commercial outcome was observed within the bounded Behavioral Ledger evidence read used for this packet."
      );
    });

    it("does not infer communication channel conflicts between explicit channel preference and intervention option names", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1", eventType: "DELIVERED", assignedOption: "phone_call" }),
        makeLedgerEvent({ id: 2, decisionPointId: "dp_1", eventType: "STARTED", assignedOption: "phone_call" }),
        makeLedgerEvent({ id: 3, decisionPointId: "dp_2", eventType: "DELIVERED", assignedOption: "phone_call" }),
        makeLedgerEvent({ id: 4, decisionPointId: "dp_2", eventType: "STARTED", assignedOption: "phone_call" }),
        makeLedgerEvent({ id: 5, decisionPointId: "dp_3", eventType: "DELIVERED", assignedOption: "phone_call" }),
        makeLedgerEvent({ id: 6, decisionPointId: "dp_3", eventType: "STARTED", assignedOption: "phone_call" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadLedgerEvents: async () => events,
          loadExplicitPreferences: async () => [
            {
              kind: "contact_channel",
              targetKey: "channel",
              preference: "sms",
              sourceSystem: "standing_permissions",
              provenance: "operator_declared",
            },
          ],
        },
      });

      // Both explicit preference and observed events are preserved
      expect(packet.card.explicitPreferences).toHaveLength(1);
      expect(packet.card.explicitPreferences[0]?.preference).toBe("sms");
      expect(packet.observedPatterns).toHaveLength(1);

      // Conflict uncertainty must NOT be emitted by inferring channel from intervention option name
      expect(packet.uncertainty.some(u => u.reason === "conflicting_signals")).toBe(false);
    });

    it("emits evidence_window_truncated uncertainty when ledger read reaches limit", async () => {
      const events: BoundedLedgerReadEvent[] = Array.from({ length: 200 }, (_, i) =>
        makeLedgerEvent({ id: i + 1, decisionPointId: `dp_${i + 1}` })
      );

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      const truncation = packet.uncertainty.find(u => u.reason === "evidence_window_truncated");
      expect(truncation).toBeDefined();
      expect(truncation?.scope).toBe("behavioral_ledger");
      expect(truncation?.detail).toContain("200-row Stage 1 limit");
    });

    it("does not emit evidence_window_truncated uncertainty when ledger read is below limit", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: "dp_1" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      expect(packet.uncertainty.some(u => u.reason === "evidence_window_truncated")).toBe(false);
    });

    it("treats multiple rows sharing a correlationId without decisionPointId as ONE observation", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: null, correlationId: "ops_task:99", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 2, decisionPointId: null, correlationId: "ops_task:99", eventType: "STARTED" }),
        makeLedgerEvent({ id: 3, decisionPointId: null, correlationId: "ops_task:99", eventType: "COMPLETED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // 3 rows for 1 correlationId = 1 observation, NOT 3
      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "insufficient_observations")).toBe(true);
    });

    it("requires 3 distinct correlation IDs when decisionPointId is null", async () => {
      const events: BoundedLedgerReadEvent[] = [
        makeLedgerEvent({ id: 1, decisionPointId: null, correlationId: "ops_task:1", eventType: "DELIVERED" }),
        makeLedgerEvent({ id: 2, decisionPointId: null, correlationId: "ops_task:2", eventType: "DELIVERED" }),
      ];

      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: { loadLedgerEvents: async () => events },
      });

      // 2 correlations = 2 observations (< 3 threshold)
      expect(packet.observedPatterns).toHaveLength(0);
      expect(packet.uncertainty.some(u => u.reason === "insufficient_observations")).toBe(true);
    });
  });

  // -------------------------------------------------------------------------
  // 9. Permanent Truth Firewall & Launch Protection Integrity
  // -------------------------------------------------------------------------
  describe("Truth Firewall & Launch Protection Integrity", () => {
    it("never grants authoritativeFor current_business_truth on packet", async () => {
      const packet = await buildOperatorContextPacket({
        tenantId: "tenant_alpha",
        identity: makeCanonicalIdentity(),
        deps: {
          loadLedgerEvents: async () => [],
        },
      });

      expect((packet as any).authoritativeFor).toBeUndefined();
      expect((packet as any).current_business_truth).toBeUndefined();
      expect(JSON.stringify(packet)).not.toContain('"authoritativeFor"');
    });

    it("verifies server/claire/turn/brainV3.ts does NOT import Operator Context", () => {
      const brainV3Path = resolve(__dirname, "../claire/turn/brainV3.ts");
      const content = readFileSync(brainV3Path, "utf-8");
      expect(content).not.toContain("operatorContext");
      expect(content).not.toContain("OperatorContextPacket");
      expect(content).not.toContain("buildOperatorContextPacket");
    });

    it("verifies server/persistentOperator/operatorContext.ts has no imports from server/mitch/", () => {
      const opContextPath = resolve(__dirname, "./operatorContext.ts");
      const content = readFileSync(opContextPath, "utf-8");
      expect(content).not.toContain("server/mitch");
      expect(content).not.toContain("../mitch");
      expect(content).not.toContain("/mitch/");
    });

    it("verifies server/persistentOperator/operatorContext.ts has no imports from server/claire/", () => {
      const opContextPath = resolve(__dirname, "./operatorContext.ts");
      const content = readFileSync(opContextPath, "utf-8");
      expect(content).not.toContain("server/claire");
      expect(content).not.toContain("../claire");
      expect(content).not.toContain("/claire/");
    });

    it("verifies drizzle/schema.ts is not edited and has no operator context, beliefs, or conclusions tables", () => {
      const schemaPath = resolve(__dirname, "../../drizzle/schema.ts");
      const content = readFileSync(schemaPath, "utf-8");
      expect(content).not.toContain("operator_context");
      expect(content).not.toContain("operator_beliefs");
      expect(content).not.toContain("operator_conclusions");
    });
  });
});
