CREATE TABLE IF NOT EXISTS `procurement_workflows` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_key` varchar(191) NOT NULL,
  `workflow_type` varchar(100) NOT NULL,
  `status` enum('pending','running','waiting_operator','completed','failed','cancelled','dead_letter') NOT NULL DEFAULT 'pending',
  `input_json` json NULL,
  `output_json` json NULL,
  `current_step_key` varchar(191) NULL,
  `deadline_at` timestamp(3) NULL,
  `next_run_at` timestamp(3) NULL,
  `completed_at` timestamp(3) NULL,
  `failed_at` timestamp(3) NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procurement_workflows_key` (`workflow_key`),
  KEY `idx_procurement_workflows_status_run` (`status`,`next_run_at`),
  KEY `idx_procurement_workflows_deadline` (`deadline_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procurement_workflow_steps` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `step_key` varchar(191) NOT NULL,
  `step_type` varchar(100) NOT NULL,
  `status` enum('pending','ready','leased','running','waiting_operator','completed','retry_scheduled','dead_letter','cancelled') NOT NULL DEFAULT 'pending',
  `payload_json` json NULL,
  `result_json` json NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `available_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deadline_at` timestamp(3) NULL,
  `max_attempts` int unsigned NOT NULL DEFAULT 5,
  `attempt_count` int unsigned NOT NULL DEFAULT 0,
  `lease_owner` varchar(191) NULL,
  `lease_expires_at` timestamp(3) NULL,
  `heartbeat_at` timestamp(3) NULL,
  `last_error` text NULL,
  `completed_at` timestamp(3) NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procurement_steps_workflow_step` (`workflow_id`,`step_key`),
  UNIQUE KEY `uq_procurement_steps_idempotency` (`idempotency_key`),
  KEY `idx_procurement_steps_claim` (`status`,`available_at`,`lease_expires_at`),
  KEY `idx_procurement_steps_deadline` (`deadline_at`),
  CONSTRAINT `fk_procurement_steps_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `procurement_workflows` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procurement_outbox_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `step_id` bigint unsigned NULL,
  `event_type` varchar(128) NOT NULL,
  `payload_json` json NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `status` enum('pending','leased','published','retry_scheduled','dead_letter','cancelled') NOT NULL DEFAULT 'pending',
  `available_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `attempt_count` int unsigned NOT NULL DEFAULT 0,
  `max_attempts` int unsigned NOT NULL DEFAULT 8,
  `lease_owner` varchar(191) NULL,
  `lease_expires_at` timestamp(3) NULL,
  `heartbeat_at` timestamp(3) NULL,
  `published_at` timestamp(3) NULL,
  `last_error` text NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procurement_outbox_idempotency` (`idempotency_key`),
  KEY `idx_procurement_outbox_claim` (`status`,`available_at`,`lease_expires_at`),
  CONSTRAINT `fk_procurement_outbox_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `procurement_workflows` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_procurement_outbox_step` FOREIGN KEY (`step_id`) REFERENCES `procurement_workflow_steps` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procurement_operator_gates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `step_id` bigint unsigned NULL,
  `gate_key` varchar(191) NOT NULL,
  `status` enum('pending','approved','rejected','expired','cancelled') NOT NULL DEFAULT 'pending',
  `prompt_json` json NULL,
  `evidence_json` json NULL,
  `requested_by` varchar(191) NULL,
  `decided_by` varchar(191) NULL,
  `decision_reason` text NULL,
  `deadline_at` timestamp(3) NULL,
  `decided_at` timestamp(3) NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procurement_operator_gates_key` (`workflow_id`,`gate_key`),
  KEY `idx_procurement_operator_gates_status` (`status`,`deadline_at`),
  CONSTRAINT `fk_procurement_gates_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `procurement_workflows` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_procurement_gates_step` FOREIGN KEY (`step_id`) REFERENCES `procurement_workflow_steps` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procurement_execution_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `step_id` bigint unsigned NULL,
  `event_type` varchar(100) NOT NULL,
  `from_status` varchar(50) NULL,
  `to_status` varchar(50) NULL,
  `lease_owner` varchar(191) NULL,
  `attempt_number` int unsigned NULL,
  `details_json` json NULL,
  `error_text` text NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_procurement_history_workflow_time` (`workflow_id`,`created_at`),
  KEY `idx_procurement_history_step_time` (`step_id`,`created_at`),
  CONSTRAINT `fk_procurement_history_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `procurement_workflows` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_procurement_history_step` FOREIGN KEY (`step_id`) REFERENCES `procurement_workflow_steps` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `procurement_dead_letters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workflow_id` bigint unsigned NOT NULL,
  `source_type` enum('workflow_step','outbox_event') NOT NULL,
  `source_id` bigint unsigned NOT NULL,
  `reason` varchar(255) NOT NULL,
  `payload_json` json NULL,
  `error_text` text NULL,
  `attempt_count` int unsigned NOT NULL,
  `resolved_at` timestamp(3) NULL,
  `resolved_by` varchar(191) NULL,
  `resolution_note` text NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_procurement_dead_letters_source` (`source_type`,`source_id`),
  KEY `idx_procurement_dead_letters_workflow` (`workflow_id`,`resolved_at`),
  CONSTRAINT `fk_procurement_dead_letters_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `procurement_workflows` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
