CREATE TABLE IF NOT EXISTS `vendor_contact_drafts` (
  `id` char(36) NOT NULL,
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default',
  `source_key` varchar(191) NOT NULL,
  `candidate_id` char(36) NULL,
  `lead_id` varchar(191) NULL,
  `lane` varchar(64) NULL,
  `channel` varchar(40) NOT NULL,
  `recipient_snapshot` varchar(500) NULL,
  `subject_rendered` text NULL,
  `body_rendered` longtext NOT NULL,
  `body_hash` char(64) NOT NULL,
  `template_key` varchar(191) NULL,
  `template_version` varchar(64) NULL,
  `founder_escalation_present` tinyint(1) NOT NULL DEFAULT 0,
  `forbidden_claims_scan_json` json NOT NULL,
  `draft_status` varchar(40) NOT NULL DEFAULT 'draft_ready',
  `created_by` varchar(191) NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_vendor_contact_drafts_source` (`source_key`,`created_at`),
  KEY `idx_vendor_contact_drafts_candidate` (`candidate_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `vendor_contact_attempts` (
  `id` char(36) NOT NULL,
  `tenant_id` varchar(64) NOT NULL DEFAULT 'default',
  `outreach_draft_id` char(36) NULL,
  `source_key` varchar(191) NOT NULL,
  `service_request_id` varchar(191) NULL,
  `candidate_id` char(36) NULL,
  `lead_id` varchar(191) NULL,
  `lane` varchar(64) NULL,
  `channel` varchar(40) NOT NULL,
  `recipient_snapshot` varchar(500) NULL,
  `draft_subject` text NULL,
  `draft_body_snapshot` longtext NULL,
  `draft_body_hash` char(64) NULL,
  `template_key` varchar(191) NULL,
  `template_version` varchar(64) NULL,
  `founder_escalation_present` tinyint(1) NOT NULL DEFAULT 0,
  `forbidden_claims_scan_json` json NOT NULL,
  `send_gate_result_json` json NOT NULL,
  `automation_mode` enum('noop_provider','gated_provider_future','manual_fallback') NOT NULL DEFAULT 'noop_provider',
  `provider_adapter` varchar(80) NULL,
  `provider_attempt_id` varchar(191) NULL,
  `status` enum('draft_ready','gate_passed','queued_noop','sent_noop','response_pending','reply_received','interpreted','blocked') NOT NULL DEFAULT 'draft_ready',
  `status_history_json` json NOT NULL,
  `latest_reply_json` json NULL,
  `latest_terms_packet_json` json NULL,
  `live_provider_invoked` tinyint(1) NOT NULL DEFAULT 0,
  `outreach_sent_by_held` tinyint(1) NOT NULL DEFAULT 0,
  `provider_responded` tinyint(1) NOT NULL DEFAULT 0,
  `provider_accepted` tinyint(1) NOT NULL DEFAULT 0,
  `booking_confirmed` tinyint(1) NOT NULL DEFAULT 0,
  `payment_authorized` tinyint(1) NOT NULL DEFAULT 0,
  `dispatched` tinyint(1) NOT NULL DEFAULT 0,
  `idempotency_key` varchar(191) NOT NULL,
  `occurred_at` timestamp(3) NULL,
  `sent_at` timestamp(3) NULL,
  `created_by` varchar(191) NOT NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_vendor_contact_attempts_idempotency` (`idempotency_key`),
  KEY `idx_vendor_contact_attempts_source` (`source_key`,`created_at`),
  KEY `idx_vendor_contact_attempts_candidate` (`candidate_id`,`created_at`),
  KEY `idx_vendor_contact_attempts_status` (`status`,`created_at`),
  CONSTRAINT `fk_vendor_contact_attempts_draft` FOREIGN KEY (`outreach_draft_id`)
    REFERENCES `vendor_contact_drafts` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_vendor_contact_attempts_no_truth_yet` CHECK (
    `provider_accepted` = 0 AND `booking_confirmed` = 0 AND `payment_authorized` = 0 AND `dispatched` = 0
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
