import { and, eq, inArray, sql } from "drizzle-orm";
import { orders } from "../../drizzle/schema";
import { getDb } from "../db";
export type CargoState="IN_VEHICLE_UNPROCESSED"|"AT_PROCESSOR"|"IN_VEHICLE_PROCESSED";
export async function listCargo(tenantId:string,vehicleId:string){const db=await getDb();if(!db)throw new Error("Database not available");const rows:any[]=(await db.execute(sql`SELECT c.state,c.vehicleId,c.transferredAt,c.evidenceJson,o.id,o.firstName,o.lastName,o.address,o.status FROM goldline_vehicle_custody c JOIN orders o ON o.id=c.orderId AND o.tenantId=c.tenantId WHERE c.tenantId=${tenantId} AND c.vehicleId=${vehicleId} AND c.state IN ('IN_VEHICLE_UNPROCESSED','IN_VEHICLE_PROCESSED') AND o.status NOT IN ('delivered','cancelled') ORDER BY c.transferredAt,o.id` ) as any)[0]??[];return rows.map(r=>({...r,evidenceJson:typeof r.evidenceJson==="string"?JSON.parse(r.evidenceJson):r.evidenceJson}));}
export async function listAtProcessor(tenantId:string){const db=await getDb();if(!db)throw new Error("Database not available");const rows:any[]=(await db.execute(sql`SELECT c.state,c.vehicleId,c.transferredAt,c.evidenceJson,o.id,o.firstName,o.lastName,o.address,o.status FROM goldline_vehicle_custody c JOIN orders o ON o.id=c.orderId AND o.tenantId=c.tenantId WHERE c.tenantId=${tenantId} AND c.state='AT_PROCESSOR' AND o.status NOT IN ('delivered','cancelled') ORDER BY c.transferredAt,o.id`) as any)[0]??[];return rows;}
export async function listUnassignedPickedUp(tenantId:string){const db=await getDb();if(!db)throw new Error("Database not available");const explicit:any[]=(await db.execute(sql`SELECT orderId FROM goldline_vehicle_custody WHERE tenantId=${tenantId}`) as any)[0]??[];const claimed=new Set(explicit.map(r=>Number(r.orderId)));return (await db.select().from(orders).where(and(eq(orders.tenantId,tenantId),eq(orders.status,"collected")))).filter(o=>!claimed.has(o.id));}
export async function transferCustody(input:{tenantId:string;orderId:number;actorId:string;vehicleId:string;to:CargoState;confirmed:boolean}){if(!input.confirmed)throw new Error("Physical transfer must be explicitly confirmed.");const db=await getDb();if(!db)throw new Error("Database not available");return db.transaction(async tx=>{const [order]=await tx.select().from(orders).where(and(eq(orders.tenantId,input.tenantId),eq(orders.id,input.orderId))).limit(1);if(!order)throw new Error("Order not found in this tenant.");if(inArray as unknown&&!(["collected","processing","ready"] as string[]).includes(order.status))throw new Error("Order status does not support this custody transfer.");const prior:any[]=(await tx.execute(sql`SELECT state,revision FROM goldline_vehicle_custody WHERE tenantId=${input.tenantId} AND orderId=${input.orderId} FOR UPDATE`) as any)[0]??[];const from:CargoState|"AWAITING_PICKUP"=prior[0]?.state??"AWAITING_PICKUP";
 const allowed=(from==="AWAITING_PICKUP"&&input.to==="IN_VEHICLE_UNPROCESSED"&&order.status==="collected")||(from==="IN_VEHICLE_UNPROCESSED"&&input.to==="AT_PROCESSOR")||(from==="AT_PROCESSOR"&&input.to==="IN_VEHICLE_PROCESSED"&&order.status==="ready");if(!allowed){if(from===input.to)return {state:from,idempotent:true};throw new Error(`Custody cannot move from ${from} to ${input.to} while order is ${order.status}.`);}
 const evidence={confirmedBy:input.actorId,confirmedAt:new Date().toISOString(),from,to:input.to,orderStatus:order.status,claims:{gpsProvesTransfer:false}};await tx.execute(sql`INSERT INTO goldline_vehicle_custody (tenantId,orderId,state,vehicleId,actorId,evidenceJson) VALUES (${input.tenantId},${input.orderId},${input.to},${input.to==="AT_PROCESSOR"?null:input.vehicleId},${input.actorId},${JSON.stringify(evidence)}) ON DUPLICATE KEY UPDATE state=VALUES(state),vehicleId=VALUES(vehicleId),actorId=VALUES(actorId),evidenceJson=VALUES(evidenceJson),revision=revision+1,transferredAt=CURRENT_TIMESTAMP`);return {state:input.to,idempotent:false};});}
export function cargoAppearance(state:Extract<CargoState,"IN_VEHICLE_UNPROCESSED"|"IN_VEHICLE_PROCESSED">){return state==="IN_VEHICLE_UNPROCESSED"?{kind:"paper_bag" as const,condition:"scrunched garments",next:"Processor handoff"}:{kind:"garment_bag" as const,condition:"covered garments",next:"Customer return"};}
