import { describe, expect, it } from "vitest";
import { BrowserLocalBoreslayDemoAdapter } from "./PublicBoreslayDemoAdapter";
import { PublicBoreslayEngine } from "./engine";

function readyEngine() { const e=new PublicBoreslayEngine();e.start();e.state.spark.invulnerableUntil=999999;for(let i=0;i<300;i++)e.update(50);return e; }
describe("simulated Follow Up mission",()=>{
  it("begins charging and becomes ready deterministically",()=>{const e=new PublicBoreslayEngine();expect(e.state.mission.status).toBe("charging");e.start();e.state.spark.invulnerableUntil=999999;for(let i=0;i<300;i++)e.update(50);expect(e.state.mission.status).toBe("ready");});
  it("cannot deploy early",()=>{const e=new PublicBoreslayEngine();e.start();expect(e.openFollowUpBriefing()).toBe(false);expect(e.deployFollowUp()).toBe(false);});
  it("briefing pauses and NOT NOW preserves readiness",()=>{const e=readyEngine();expect(e.openFollowUpBriefing()).toBe(true);const t=e.state.time;e.update(5000);expect(e.state.time).toBe(t);expect(e.closeFollowUpBriefing()).toBe(true);expect(e.state.mission.status).toBe("ready");});
  it("stages $740 visibly before a delayed strike that resolves once",()=>{const e=readyEngine();e.openFollowUpBriefing();expect(e.deployFollowUp()).toBe(true);const hp=e.state.boss.hp;for(let i=0;i<150;i++)e.update(50);expect(e.state.mission.status).toBe("final-result");expect(e.state.mission.dispatch).toBe("SIMULATED OPPORTUNITY · $740");expect(e.state.boss.hp).toBe(hp);for(let i=0;i<59;i++)e.update(50);expect(e.state.mission.status).toBe("final-result");e.update(50);expect(e.state.mission.status).toBe("strike");expect(e.state.boss.hp).toBe(hp-20);for(let i=0;i<9;i++)e.update(50);expect(e.state.mission.status).toBe("resolved");const resolvedHp=e.state.boss.hp;for(let i=0;i<50;i++)e.update(50);expect(e.state.boss.hp).toBe(resolvedHp);});
  it("mission reward produces exactly +12 net influence and restores resources",()=>{const e=readyEngine();e.state.boss.hp=100;e.state.influence=40;e.state.spark.energy=10;const time=e.state.contractRemainingMs;e.openFollowUpBriefing();e.deployFollowUp();for(let i=0;i<210;i++)e.update(50);expect(e.state.influence).toBe(52);expect(e.state.spark.energy).toBeGreaterThanOrEqual(30);expect(e.state.contractRemainingMs).toBeGreaterThan(time-10500);});
  it("ordinary Fire Breath retains +4 influence",()=>{const e=new PublicBoreslayEngine();e.start();e.state.influence=40;e.state.boss.x=360;e.state.boss.y=e.state.spark.y-35;e.setAim(360,e.state.spark.y-35);e.fire();e.update(100);expect(e.state.influence).toBe(44);});
  it("pause freezes final-result dwell time",()=>{const e=readyEngine();e.openFollowUpBriefing();e.deployFollowUp();for(let i=0;i<150;i++)e.update(50);const at=e.state.mission.finalResultAt;e.pause();e.update(10000);expect(e.state.mission.status).toBe("final-result");expect(e.state.mission.finalResultAt).toBe(at);});
  it("restart clears the final-result and strike lifecycle",()=>{const e=readyEngine();e.openFollowUpBriefing();e.deployFollowUp();for(let i=0;i<150;i++)e.update(50);e.reset();expect(e.state.mission.status).toBe("charging");expect(e.state.mission.deployment).toBeNull();expect(e.state.mission.finalResultAt).toBeNull();expect(e.state.mission.strikeAt).toBeNull();expect(e.state.mission.rewardApplied).toBe(false);});
  it("defeat prevents delayed mission reward",()=>{const e=readyEngine();e.openFollowUpBriefing();e.deployFollowUp();e.state.status="defeat";e.update(10000);expect(e.state.mission.rewardApplied).toBe(false);});
  it("victory prevents delayed mission reward",()=>{const e=readyEngine();e.openFollowUpBriefing();e.deployFollowUp();e.state.status="victory";e.update(10000);expect(e.state.mission.rewardApplied).toBe(false);});
  it("adapter returns ordered explicitly simulated results and no production capability",()=>{const a=new BrowserLocalBoreslayDemoAdapter();const d=a.deployCrewMission(1000);expect(a.advanceCrewMission(d,3500).stage).toBe(1);expect(a.advanceCrewMission(d,6000).stage).toBe(2);expect(a.advanceCrewMission(d,8500).stage).toBe(3);expect(a.resolveCrewMission(d).simulated).toBe(true);expect(a.productionMutationsReachable).toBe(false);});
});
